apiVersion: v1
kind: Secret
metadata:
    name: bytestash-secrets
    namespace: bytestash
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:XElCn3O+sZMD6fv3CNGqCBolVt7T1lgyvUXNLnK1TtMYMaLyKOfmMndhbQQT5o0kaNELeQinVcUVQxR8/aOZbw==,iv:VwvdU72ero3twDveCh4e1oTdWqoYJawafkS6T4ID7Q8=,tag:/TA4PCyEme5I83RytUHNMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUGNzNzI3aFkyQm5BWjZz
            Q2hpb3B3SVlmZUNwNUtrM3V3SDg2bGlxVEdRCjRWSmNxRTFCMSt2VWRabHhwK3lK
            WWJEM1lhK3pLaEE5YnlEekNrTTd0bVEKLS0tIFJMVlYxejVUS3c3WDJWbkVyT21n
            alF2UGRaMmk3WFMyKzJsTDVwcmNMRWsK68QvbeGzY+Eu9Ko9tOCs7RPBTfo/Qhrs
            8g03xujTVETEfAd3hd1lgoX9spcGkzcOPZnUQUPUXWkYpd+A23qcqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T00:12:20Z"
    mac: ENC[AES256_GCM,data:dfF9mcXWdAQrxl0lHYuYeeeExlC4r6y+Kl7MrfBwtb/xdBQdcWW+4QI2SoLU6Mlfyw7TdKi61PDecK0wFiZx/fEHyfEk+JWzU6AKuwotU4/pa6iCesXl8pMqovwop7UU5nRMd76+NqxL2uS5rI2+mstKXU4JuAa6aAdVS1IMIGY=,iv:qOaZvUJeTYNne3vAnhaVtK2OXsek6WpCFercMooVzsY=,tag:In27CzphfenFybUQpJMEvg==,type:str]
    version: 3.13.0
