apiVersion: v1
kind: Secret
metadata:
    name: openhands-postgres-app
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ndpxeDuAQbjJ,iv:CY2lXk3oU70NuWDUmJcqe7tOSG7+1H8G+EDTskZkPcU=,tag:ZCPVR2xIHKb4RKpgI0q2kw==,type:str]
    password: ENC[AES256_GCM,data:VfNSFpmRmPVICY+E4uVFtHrCiyF1uTI1n56wQMx21UYn3hCbmJSB0Q==,iv:k91OHBvgo6GrUUigcUZj2MhnINss1riN0enFdoCSLEQ=,tag:COI0w/KdyWdCZSX/QHe5JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzemYrWUxYTHZUMlVacTlu
            Nm9wVEhxYWE1V3g4YXBISjl5UkxCd0FaWUZFCmxFc2p2bWdsbHpQNWt6WTFKc2ZY
            UlVKWlliTE9hN3U5SUF0SGVUaFRaOWcKLS0tIGQwMWhRSFEwaURBYkhsRnFvbFQ3
            NklQcnZNcjUxTkdpZnBONDhnemxHTm8KuAYCwKkqZGLuUxvaNfTWleD8IP17pU4/
            Bm+t/JzYh0qDHKf8Y877LJmR9BJt1NKW7RM5z5oYYmeDpRnVGEHfJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:51:30Z"
    mac: ENC[AES256_GCM,data:FWKXtg9LzRc9qeOUxoLf6xiGGO40gn87jnm12N0mbyEX6gkoyM6gwKRGBOKLbZzDVARuMVLvbON+NKDmzbh0Rsyv3jlM8TmTHTVhpMk7HLaMpENX2IavCo5LEAVgOyw6jl9JkBDR23h5oMra47fJZYcUOixE8wEe++EIrniJD8M=,iv:C1ygTWlUiktH+V7edplv/y9ftyh31uLuUa10957chus=,tag:s+5Pe4w4on4vMTiySb0A7A==,type:str]
    version: 3.13.0
