apiVersion: v1
kind: Secret
metadata:
    name: platform-postgres-app
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MPlS7HxcUTQ=,iv:nwZKzGH0f9uSRUI/1lOHloQFIepcOcF0s3MMC1dWy/0=,tag:sTVbObJtPSUIS/I4Q3wIsg==,type:str]
    password: ENC[AES256_GCM,data:QWzm9F/5OOeEK6sWTwsKjbf199XfjhwHt6UVOc4T/7s=,iv:yoicjc5OPk/XEhU4euhyy0Vx0UuopmgjmKggDbclfqU=,tag:+VnR53GhM/b4XD2Ae1fqYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTlWYTd1ZXVKL1U3dE1h
            ZEJMNDJHVHl0NmVUK0FBYmxFVDl5WnAvcVZVCmpmUDQxU0F2dG9HWWVHMkl3ZHRJ
            OUxrRWVNY05VWktoeHVpbm1PODFPSFEKLS0tIFBOZFZhcG9OUy91M2N5RUg5ejV5
            TTVJbUJzMVROQng3OXlMeE1lRGtya1kKjPwBMfWHhcv4WRXVUWoy/SbaGiCY1KGh
            Cn4kGa1iKK4/ybm5qNQjUi58JwmwAYPZ0sZN9u+eS8XjCwGx4ru+NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T02:50:40Z"
    mac: ENC[AES256_GCM,data:Krmg41cdwff4RHbOAVyte+uFki5SwoaNIP9o0D05IUtZK1+IW18HIMyBxEZNtlHkBDwVh2VBSnjHhM4s1P2JU0Qp+m3CWG4Kdn4B2Wxdd9fZNlBzDWceGk24MaBPIQwN28VhkZZzzp1Bx1RWgepOTk2zcAR8rRP9lg2FIPTe5BU=,iv:uzIdePP22Wi5mtkTbYVR3QjbQWE1yB6P6rf22TIqRYM=,tag:6QiFA/Kp1pWuqHlyKUCDNw==,type:str]
    version: 3.13.0
