apiVersion: v1
kind: Secret
metadata:
    name: platform-postgres-app
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MPlS7HxcUTQ=,iv:nwZKzGH0f9uSRUI/1lOHloQFIepcOcF0s3MMC1dWy/0=,tag:sTVbObJtPSUIS/I4Q3wIsg==,type:str]
    password: ENC[AES256_GCM,data:qgjWzZ4zParEIW4eBadvlMuyo/qRk764yHmb2Tsbnd4=,iv:CCc8RRqoHNkqSdOlXkDls3PBMNjuq4WajfnSTT5Yx+E=,tag:oh6y5Io3SM2nhJI0iztylA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTlWYTd1ZXVKL1U3dE1h
            ZEJMNDJHVHl0NmVUK0FBYmxFVDl5WnAvcVZVCmpmUDQxU0F2dG9HWWVHMkl3ZHRJ
            OUxrRWVNY05VWktoeHVpbm1PODFPSFEKLS0tIFBOZFZhcG9OUy91M2N5RUg5ejV5
            TTVJbUJzMVROQng3OXlMeE1lRGtya1kKjPwBMfWHhcv4WRXVUWoy/SbaGiCY1KGh
            Cn4kGa1iKK4/ybm5qNQjUi58JwmwAYPZ0sZN9u+eS8XjCwGx4ru+NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T06:30:48Z"
    mac: ENC[AES256_GCM,data:dD2O28ZTmzXA96hwRrcyhDlaIlyUWFCUrkPX+D64N1VNZfiIVinazjIJT+U5j2mqoVzG/4KtCO9PovmBui6+wrhLm2u3hRjbRDhupm/r7fd8/309UTY02b7i73qvSgmLH1hJXNbrE4qe+hV49B/JbJoRrRHnSBq9H5w5875ukGc=,iv:ALwQAKjmrP8g2YNeVzVrgCDhXHWWaiG+YYb50TNTzUQ=,tag:rDGV/WIUzFDFymoHw9t21A==,type:str]
    version: 3.13.0
