apiVersion: v1
kind: Secret
metadata:
    name: platform-postgres-app
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MPlS7HxcUTQ=,iv:nwZKzGH0f9uSRUI/1lOHloQFIepcOcF0s3MMC1dWy/0=,tag:sTVbObJtPSUIS/I4Q3wIsg==,type:str]
    password: ENC[AES256_GCM,data:RzxPhC97ed3De6GrvgRhpjF1Bq55P0dvfjsycoDS0rc=,iv:5CbRWOh3a79AeOwLIug3lLEVaGeFo1MIsHedIPkDfjA=,tag:64JAPrzHXKKdmd5GDk096w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTlWYTd1ZXVKL1U3dE1h
            ZEJMNDJHVHl0NmVUK0FBYmxFVDl5WnAvcVZVCmpmUDQxU0F2dG9HWWVHMkl3ZHRJ
            OUxrRWVNY05VWktoeHVpbm1PODFPSFEKLS0tIFBOZFZhcG9OUy91M2N5RUg5ejV5
            TTVJbUJzMVROQng3OXlMeE1lRGtya1kKjPwBMfWHhcv4WRXVUWoy/SbaGiCY1KGh
            Cn4kGa1iKK4/ybm5qNQjUi58JwmwAYPZ0sZN9u+eS8XjCwGx4ru+NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T06:43:55Z"
    mac: ENC[AES256_GCM,data:/lDtjcAH6YsPFa8fSclyy7gLapQ2yW+LDnW2wpnM/X/xTQrWaOeEif2f/2FF9FZPWuRzkEWQiY2kp/hQgMoSSlRMi3rW4n1VsROaxHcesXMFXUKKrGIS0tsNf9CojClMb3qle19w5WRVJ6DDoPkmniNDNxjq4LKO6wLIv9jT3yg=,iv:AFaqivElluhoklwg5uPtFvlLvxLtlkEoy0eK4cyrinw=,tag:xoucPgpZWqI7CfPc/v4dzw==,type:str]
    version: 3.13.0
