apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: platform-postgres-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./platform-postgres-secret.yaml
  - ./openhands-postgres-secret.yaml
