apiVersion: v1
kind: Namespace
metadata:
    name: openclaw
stringData:
    GITHUB_MCP_TOKEN: ENC[AES256_GCM,data:n6qMvJWteAyDwpBoeDOxVjoT8+AEClqwfFXA3ks4L9iKNNFhhJAR/rt5XDgrZHETgegqY59VpooNxwfHNvFs1g==,iv:DBTwx8s6IXxl1pWUMN1xVOryTh4/s6zMN2Ci3B7aNAE=,tag:UV1GggsOG85BCNDqdhDPxA==,type:str]
    GITHUB_APP_PRIVATE_KEY: ENC[AES256_GCM,data:YE/CRHhd7147gKkORq9tHCXibr+CkgtYj7+jIf1LzzJXuDoGFLdrxs05C4lxHz1ztG5fhZDllba1IPt8tNDieLNLkhx5vfqu1Vw4LV8j0+LBnLjnGH9z+jlproJGPZKkEcgIWTUESuCRTmQYVM0ik7EnuVstS9LLLzBCdJy1pHcpY83oagVeBhmLpSzfpDWIhIf2JX7dtlADZkG/RVFkvGkLBRWU8FU7nMYUwsHqMqU52ahO98X/eWV3rfgIPleZANPaW1mdnh90d3ZZTeqJHn6BSbo7Zjy58YNpgP77n9elIr1310tyh3hFIdcAsScvfiSo+qYKVBgpsiMjygSQ5zI/M+I/Sl0TAfvsUFWX50GIBTX9AjFV8PzYepxxKaLDigeKaN8tlUYlo7qXDY6pJNwWUGi72C5PskofG5+44GMShNLZ3VJs0OPz8GctG7sMVoBfvVUvOEQXl0axw5LWmgxFkZP3xTeqED+5PqCWu4nqY1lpAqasb+XbZRWF8/TCFMfQT18svlhixOQOt+dKwGre1+fG+340uBn6KnPsVGw3wpmIxYqx0gSPr0pE/yd2jOpgeLdsAwleGzrXJTHrZlL0jBZ/F/zAi8JZLqVZv3yHTpHp/EsaywzakvS6rD+gocpLy7g4Oyetp1KUTijgEvhCydlVAysa6nCcG4T+3S34fbsOyM8llQTngkbNZGxaTVEIhm9SBeA4lvseRP3j8UGvI+AUHYM/i9hDv0nB0snAwmXUnruIbvChTZrPk/qh3oFx/hAlvljUp5rQp1rvb9LGTEOBTwRvUqf7g5e/rlSYhiCSm9ynVs2+OxJ08AX4XmBz3LNjKXpVliYXOnE7qAq75NLhRAkl1H/gQXT1LBxXch1WRtOEIXccKGJ8jvb4mK9xRkJIxm46EfDWOfUjzm4hYq6y7H3H8bbrBB4SEZVW3LfiTPpCPCZIV7qv2A0DN1/4FPlLA81kni4Ke4+F5S5VCO2RWNVd112YgenjiWO30mf8dmpYtXXYDvWLgtXfzYE2+5l0APUv0gpzcqYgLi3u6qTb9jaixYgMfmkSQhZaXhaZBXdugXg8xM2HYp4LCAonHyaQ6bGoRAiHq8GVpTLBNNDhviPiTXvwFu2nuvGr4E76nmDzLjNArPwz09LtgoYTyLQYJOl7bJ/fmro+o+L5F7NAsyhQqIRzJyAja+KcCr0tiq+DqvH6Bz7SN6/C+aF3F3kAMr2QixGCxoXpS9Yq6WK6UngyyQUzEko9osMEEPcJ4yRzJi4Zcs6Bv4CJRoGTWmbbzDX5TDbVENPlOWgYELgMLfxUZeHzKRqVMypVG2GKFLQHUo/uewmF8Mc5ONdFBbsrs/4DLK++5o+gWiEcnuZbPEiKsasd6dZMF7+6b/INIf5/34NxHiuYQg1KOepgf5FswILJCdqsbj0nbK6m+VlPp+XlORlKYVQg4VtFw6Vri/D73GQqsEEyJjyJ0YRsUQ5DaozDK4EnZ0aqpGrVOwURTF7c5B67oow8uobL89JYWL8ypCDlasVJJu9E/HYnnTd/ksyj9w+x61NHqMm6Hj/ka54PkuJ+/Xiz6dNfU9oMvUWwT0AW9qEHRAudIS+eVIHTDwkeprBzDYFy7iNH/7AW7HED2nNbWYIxD5SzUNZ25pcmhN0g3MFzz1ymo0NsQ3Td62uDtVzxfqouucM9lQ3sEIfatEN4w4I9xDpHQ10xyj64NzSAY9O2mbrRv3qR9E1ookGqMppQ+2quHjlyrA9Z9f3oek9gyDI+iXLkg9Bi0gUL7cVQBuJh//Pp8EwuHaiXuSIEl9pUpZjd1eke4VyNSCMmK08gNx8NLABv+deg60zNmSvtS8KWTedAvaaKyOYuAoYZ/bsYDQ3CBQtuKeewJf8taDVEcJtyjf3Z7d1XZ1jBtvioPkJtSygqwpWkBGw6kv6pPCx2RJCiRbg4JbmCGTFw0aDB0hE6wBKajYGTBxn2ROnGDxT4Lz/xipcwVqsrpoUQMFVAM17Gn8uw19+s4H0vAu5AUtAnMmmuxhABy6HOJfhCMNP/9VO/jziQhj4rTu6eRyQ0ulD5iFsdW3Lrppf5f+cSon6ek53XhxkhVxEnHUzrwygC5XCZ3xlsu0nWPZBSPtaDnMQrleJE1ANRgY6OlJ6u9bKC/SpOaUaFqAl2gaThE82nyoJuctqgp4tl6+ZrJ3IwDsNojg8KEuUOIOFC4oMHLvoSUkHkAMurtydDLdo8Dg9hJsU=,iv:v3ePavp+QLUY5N0eLllM+00HB51zz0wndWYA4VZLqJc=,tag:ksYcNGI0pWXmMkSIslIo9w==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nm8rRmZwckN5S2g2V3p0
            YU5UMDdFVzZQWHo2WDg3cDBWMVo0ZHdsVkI4CnJaWVcyNi9YYWFFVjBhYjlCanV4
            djJmNmZjM2lkMm9jZ1hIUG5iZkhwWVkKLS0tIENDSCtLUnB2VWxaRWxHOFRqTFhE
            Q29hcXo3UnJGMHhvMlkrOEpxc3UzSEUKNZeVuivLM+pDnzaRo1VksUabhjd4PMiL
            s7XE1AXEO2XYbo0naitCvF2kf6KT08Am+mtgYbyl6s82BIQ5zC4khQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T06:13:48Z"
    mac: ENC[AES256_GCM,data:keHHCfidONm26v8lldLNTfvlWIOqknMPY4RH/oqI77ZE4IotzyDdv3dmkBNu5HMlebOXxV9sz1n1aBXH7wLHnE4KUZYivjrwWnGOknX6pH+x4/lbNTXhQYVkG3b2nnnGCFm8H208nTQNcyVV5cvVaa5e/z69QnXRRXRUzZ6PmTs=,iv:XrOpH9JMUMx1fGr+qeOlIJXOLERlI4pz39nBtWKwlg8=,tag:u//xCOx0/YG5PAQ/+MCEYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:R6tBNQ0JUPh6OlD5Zzr85L58XN5jn+V12zV46eOsT6NTE1X8A2+2AZ7GxWzbecNP2gqojJN17wRKMn0mvpP0oWEi4RzQyIamUPtZ0HgWh+e7E3EiM2nMPRoN5IcwRqS0axdr3TZwxNPArUA/,iv:OFGEUlHH7/gR40eSjMrw+ylv0/zg38WSZ2W7r8pqiOc=,tag:0kMAKyMz52y2YACOD4BIMg==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:/zBGWA7joVa5mQ4Ko+D4BGiwXAl/+8MYKGDKc6BVLA==,iv:lycJFtTJ3dzPrT9WRZ85ZzCo4p6QJWU1P1jBoQUzVJE=,tag:l2ixbTLzAeg1YZK2G82D2w==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:7xW6X5+vob63Y94w48nS7Y9uZP3prA0gj0wlMGQNfg==,iv:/xF8Dv3dM5OO5c/Rxnhp/zf/bG9pFqkPwMKx0dPowcg=,tag:8HfLdDrTmi0PMKqQLAqILg==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:MYTfRRtop0vo12NwyiYncPgAXZe/664nv7C7GsYtR/B/nEBYOwVniwRJfYxoTMZm4O186St4VNnLrhjJliDLxw==,iv:X07RVG0tm+Um/UuwMEW2iSwb3/ZM8lb02nU1BEpWfBo=,tag:RITHNui/ExgCFsGYl0aZeQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:rNYviJYE2lGYLdZZZtrnZBgHw3FEODlvdCMxxrZVErHohFAQH32oQT84UeHgOw==,iv:bJ/kXu14w6mTXTdEe7GkDsvYFmyTbzttY8VyqaO39GM=,tag:Sy7AEfR1VAlWUVJzrw+inA==,type:str]
    XAI_API_KEY: ENC[AES256_GCM,data:q3g3r+iY+UTYFayGP6XSSg5t6Kjrmc3otRCEaQ7ml6DHDqnDp4Rw7vHUjGDOJ+yDXeyan54JNE+dpzOQdJAYes9CvctrB7EiZwtVtqEOihyIx/Rc,iv:jYqQ8wfe2Tlvk02HUiSMSyetUfyjPBbF7dYUViit4Nc=,tag:CF1mmAyHOGon+TZbRkY98Q==,type:str]
    NOTION_TOKEN: ENC[AES256_GCM,data:tW8xq1tqLDxPfgXLlalId39EJ/uEn5fbGk1MHpizJZYIp2x7JPm04mZA7VYptwRS7GU=,iv:MFmhXI+zf6UokRtgx14ot8HgtxNQoUGwMgV9hcABreM=,tag:fhE7B6A4ytnrrgUfpyq69w==,type:str]
    WEBHOOK_TOKEN: ENC[AES256_GCM,data:kRTJuWTF74nmn5M0+4DTBN350n8RRUy6lHVZs4ilTdGd9GWginVnsULIHvJqufJw,iv:+voxsDmQt97FgV7D0Spi6Y/ZkQGZ54YnQA8BNwsQXLM=,tag:Iz8QFChnZDzn570uvbGc2g==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nm8rRmZwckN5S2g2V3p0
            YU5UMDdFVzZQWHo2WDg3cDBWMVo0ZHdsVkI4CnJaWVcyNi9YYWFFVjBhYjlCanV4
            djJmNmZjM2lkMm9jZ1hIUG5iZkhwWVkKLS0tIENDSCtLUnB2VWxaRWxHOFRqTFhE
            Q29hcXo3UnJGMHhvMlkrOEpxc3UzSEUKNZeVuivLM+pDnzaRo1VksUabhjd4PMiL
            s7XE1AXEO2XYbo0naitCvF2kf6KT08Am+mtgYbyl6s82BIQ5zC4khQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T06:13:48Z"
    mac: ENC[AES256_GCM,data:keHHCfidONm26v8lldLNTfvlWIOqknMPY4RH/oqI77ZE4IotzyDdv3dmkBNu5HMlebOXxV9sz1n1aBXH7wLHnE4KUZYivjrwWnGOknX6pH+x4/lbNTXhQYVkG3b2nnnGCFm8H208nTQNcyVV5cvVaa5e/z69QnXRRXRUzZ6PmTs=,iv:XrOpH9JMUMx1fGr+qeOlIJXOLERlI4pz39nBtWKwlg8=,tag:u//xCOx0/YG5PAQ/+MCEYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
