apiVersion: v1
kind: Namespace
metadata:
    name: openclaw
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDJCTW9GcnJuY1p0Z2hR
            MlVwY0Y2dGdSb21hK2E2Qm9PTUJ3alhjU0dFCm9FS1lXQWxhcStET21wQzJpbDBk
            MUt0YkthS25IQktBeWVETnpJL1JCWUkKLS0tIFk1RUFBT095MU5QSWVEdStzRnRj
            TGswaDB6dXNNKzNITVRlUCtmTUNGQ2sK12W9I8EkJg7gV0puqMvcNf3cx6BhQ8IX
            c7aZx8uypdu0GaSULqvksEN/4cdnZz4QUpCYyKflt1uwb6IFvm3L8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T02:33:04Z"
    mac: ENC[AES256_GCM,data:J4v2ScLgGdzcVCJ36XYKUEN43P3yDeW4+gmFjnSpZi7wx/XSybZn7Di4BAEIqG1BmdDSQO8H2Og39en6/oVqXXWjRzdYLHRy8nKug7PbRteNi6/TT40mknfxFD52/8m3pE9GIjlkBTIs2rSTKI0p8tsCTwU9N9m9Nc7RHlYBCoc=,iv:a76hWx20mHKGJvWPdicyDIZnil0LLNO61Y5f/8J40EA=,tag:0vzDtd6lm6cJpdTyvugNjA==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Ku7GlewLpTc87cTRSceQZBVTjVi9sIajghQ+/fqM8KLL5nzgDPRseizS/nNsq66AfRfdyWCZ5vcm2JQDXc32TKJR1B9s7BJEvr68mBqVCViZ4dcnXH++IhBsXiM8H+zJ+sAY+BWXDzweGYvb,iv:WcjxGxuiKF1HgPs7C9niJxdf0C79BZ2SzXcH34M6has=,tag:XcSYXAbcRNlSAPN9BDSRuA==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:XdU9VQNoE05G2ksUimMOTTUbEwj02tnq6rdpEdoS/A==,iv:CaORwCzgJ/8TIUFRGV2H8azActlLcfgV04fwJMG4fbU=,tag:gPIXNh/OAfDmIYQUYM5yDg==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:jvHSK2x00319W6lnGAg94hhHr1DK+YaCjwMVlYgFxQ==,iv:lnsoe8XNBgDL55d4zkD8xSy6S/spP4RCrveqNxDaIIo=,tag:pPvm7eXVkyk30EtkqagaVA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:hh4kvTdOGdXtticO4hqQkFgOnmUFnYYTSE/04RSnFYyBfPulJVuvEBHaI2fHxP9G3OlgkuokNiewFnDSRpDwzg==,iv:Wd75uUrutlTt1DGxYoEb2GAN8uIxFqYEiV3A5U/Npdk=,tag:zp8iV9ad5t+XCJczoN1YvQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:socZ8pdmGHwp5a37EtQ5SL8RoEeI2Qpzr50LPweyJy/K33ql2xhpJir3D52DJg==,iv:cKkTtZQ4BdG6fY0XYj6peTk2K4QX2mv/ITE7zXm30K8=,tag:PeUoCwvDwg4tp3yL1xqwZw==,type:str]
    XAI_API_KEY: ENC[AES256_GCM,data:JEPATlXRyFKM4AkjVoroX8P0+NKP58ZD2bXEZVvs3COBi3Fa1w5C+JbLOdbRffEbwW12WrT0+44cbhvnxegmDN3SUzgv8uKzVF8P6/Ys7vk24ru9,iv:JRmuaV2eGRNrV51LsmLylrbV/2MZf8YEO9xaPN3Tz7k=,tag:j2Rk8mmVDHdHBfgQ07stvA==,type:str]
    NOTION_TOKEN: ENC[AES256_GCM,data:ML4WjzbV1/CZPfgjwAnFaL8cicGe3xNGn18vbZ9UW/vv7+q0Z4t6h1KPFVL53FeQ/+I=,iv:6RC0xRa7lB0C3XO9dHMAdgQQyUUP1q5eLEqcsSZOIF8=,tag:PbPwhNUdw2dZ6r3hCosDjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDJCTW9GcnJuY1p0Z2hR
            MlVwY0Y2dGdSb21hK2E2Qm9PTUJ3alhjU0dFCm9FS1lXQWxhcStET21wQzJpbDBk
            MUt0YkthS25IQktBeWVETnpJL1JCWUkKLS0tIFk1RUFBT095MU5QSWVEdStzRnRj
            TGswaDB6dXNNKzNITVRlUCtmTUNGQ2sK12W9I8EkJg7gV0puqMvcNf3cx6BhQ8IX
            c7aZx8uypdu0GaSULqvksEN/4cdnZz4QUpCYyKflt1uwb6IFvm3L8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T02:33:04Z"
    mac: ENC[AES256_GCM,data:J4v2ScLgGdzcVCJ36XYKUEN43P3yDeW4+gmFjnSpZi7wx/XSybZn7Di4BAEIqG1BmdDSQO8H2Og39en6/oVqXXWjRzdYLHRy8nKug7PbRteNi6/TT40mknfxFD52/8m3pE9GIjlkBTIs2rSTKI0p8tsCTwU9N9m9Nc7RHlYBCoc=,iv:a76hWx20mHKGJvWPdicyDIZnil0LLNO61Y5f/8J40EA=,tag:0vzDtd6lm6cJpdTyvugNjA==,type:str]
    version: 3.13.0
