apiVersion: v1
kind: Secret
metadata:
    name: protonvpn-wireguard
    namespace: torrenting
type: Opaque
data:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:JNlopDF0Mzr7nNTRL3Sl9A==,iv:vpmQ+NuNS326ofVefR0F1CD1/v/I5KXW6KKe6i8JwHY=,tag:qrIfL9ZpGA9hziWZK97BIw==,type:str]
    WIREGUARD_PRESHARED_KEY: ""
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ark/KtUMqIG+m2mCLxliUC5X9As3PYnHW74LtH540gP8vnm7PGQi5+BglBSTLX2gDhbub+D4Rm7i1APl,iv:s09EtNhwuZAT0FUJVNV0YOMTYLhbP52q8yqWq0JQG3Q=,tag:k9NIvT1aqgIqfmk+sUUKEg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:dScEQ8z8jvKIrIlRjqDE1r7rgFkvh7JXpLo8K4ZZyXLz3vmLKr1oBXmxdVCl4jkikXpqo3Op3o5X7qC/,iv:t01fQWy5JPXJuuSWDiU9pYFCVaX5m+JmSGkdqwafh+E=,tag:VcWEFj8KSlNPA4EGnGPvSA==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UEFyLzk1WUc5WGRwQnkr
            OXA3KzhsRytKS1hzeHVlRFIvYWJUVmFSbHlBCnNLcnlsNkV4QUhFdjg2VkhaOXJo
            ZkNBVWtPUGV6VExsd2ZycXhEK3JKZ2sKLS0tIDFYVnoxV200VDJhc2Q5aUR1ZW4w
            dUpVTm5ZZXgwNU5GYW1ZbnRuQkVjb3MKz+IaVsnlhQ4YzVwTlmGVUuIMpPJuFIOf
            zj/tLx8aMklvAXct+zelIx8fuj5qnLa1TbqiOJA8Wm9980ZjBmQcGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T22:11:29Z"
    mac: ENC[AES256_GCM,data:GX85BujLRgXh4qqQDphmj7NnOjI+QQS+ySWIk3U2HBa2XYUAbuaAC9Kd4k5r5UHivnVh06cRXC/nAW66GyryCqYRYMrEWRIQpYqFqndwNiHvRvfqWKwAU/BwfXyBTFp98TP6qYuPBcQ/HxF5VzaGko9+NEhNOrdYsss1uRLLw7Q=,iv:kPUPK0GHOJW/LzwZOeP9cYcg8kXLczWn2L7akM7ONsQ=,tag:DW4klRlK58b5ISxKqSHhUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
