apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: protonvpn-wireguard-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./qbittorrent/secret.yaml
