apiVersion: v1
kind: Secret
metadata:
    name: protonvpn-wireguard
    namespace: torrenting
type: Opaque
data:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:JNlopDF0Mzr7nNTRL3Sl9A==,iv:vpmQ+NuNS326ofVefR0F1CD1/v/I5KXW6KKe6i8JwHY=,tag:qrIfL9ZpGA9hziWZK97BIw==,type:str]
    WIREGUARD_PRESHARED_KEY: ""
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:il5dXFv4ReCtTwLJlzEkqFRuZ+DpWTEtkDms65jX4+TTQ0Vh4vt4jtmefnhkwWqBenzVKvwr3AnYGGm1,iv:86UIaucmedgD4hHX0qdJA6qwv1xQm7RhGmMiC+2d9Zw=,tag:4ppxFn6x1Q7Ipr+CLKLX+w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:dScEQ8z8jvKIrIlRjqDE1r7rgFkvh7JXpLo8K4ZZyXLz3vmLKr1oBXmxdVCl4jkikXpqo3Op3o5X7qC/,iv:t01fQWy5JPXJuuSWDiU9pYFCVaX5m+JmSGkdqwafh+E=,tag:VcWEFj8KSlNPA4EGnGPvSA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:xF5FYIaBKZGNLBGcwOtFDvGetsY=,iv:1fme8Ex1l1EqQ7hTWKf2b1ZNx4C3xTNgXD1r9prqL0E=,tag:IbchoI8u1o+cEEFDe2ZwHw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:lunxrVxFnqU=,iv:WvRCrceHkZPX2VfWHk2P4iojAU7B5jlyqlMqZ5EAdJc=,tag:CGWTIR6dV9BSwtraWZvAUw==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UEFyLzk1WUc5WGRwQnkr
            OXA3KzhsRytKS1hzeHVlRFIvYWJUVmFSbHlBCnNLcnlsNkV4QUhFdjg2VkhaOXJo
            ZkNBVWtPUGV6VExsd2ZycXhEK3JKZ2sKLS0tIDFYVnoxV200VDJhc2Q5aUR1ZW4w
            dUpVTm5ZZXgwNU5GYW1ZbnRuQkVjb3MKz+IaVsnlhQ4YzVwTlmGVUuIMpPJuFIOf
            zj/tLx8aMklvAXct+zelIx8fuj5qnLa1TbqiOJA8Wm9980ZjBmQcGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T02:10:45Z"
    mac: ENC[AES256_GCM,data:1atfhvHaFyjkCmSlr5jX8Cml7/5tapAZ904Eg2lC2X3vg9HjeXle41zMqfV4YRgIM30R9Nq9gAgIMoQTeFWHVKaRXs9AdzloUYKPsc35N3lwiE/DR7P3rn+zt/bknh6jEUFCDJH3mPVfxmzUsFY9RplULofbVgsD2TkGENEPQrQ=,iv:wvTDI7RbII5Jia8pHTuzzFJaT6g/RuqJ3N9RTQg4E8o=,tag:NknDOnZEDJvZl5ywOpEEdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
