apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "100"
        - name: TZ
          value: America/Los_Angeles
        - name: UMASK
          value: "002"
        ports:
        - containerPort: 9696
          name: http
        volumeMounts:
        - mountPath: /config
          name: prowlarr-config
        livenessProbe:
          httpGet:
            path: /ping
            port: 9696
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: 9696
          initialDelaySeconds: 45
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config-pvc
