apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
  labels:
    app: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
      - name: memos
        image: neosmemo/memos:stable
        imagePullPolicy: IfNotPresent
        args:
        - --port
        - "5230"
        ports:
        - name: http
          containerPort: 5230
        env:
        - name: MEMOS_DRIVER
          value: postgres
        - name: MEMOS_DSN
          valueFrom:
            secretKeyRef:
              name: memos-db
              key: MEMOS_DSN
        - name: MEMOS_INSTANCE_URL
          value: https://paste.victornazzaro.com
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
