apiVersion: v1
kind: Secret
metadata:
    name: memos-db
    namespace: memos
type: Opaque
stringData:
    MEMOS_DSN: ENC[AES256_GCM,data:cXr0e2BxlLSx6uG+aWo4pClX3iGpV/3tlWyI1qtC3Yr3iBxeYMJCd1fsuWIjFfzcflByzLvZaM3tx/IP9D9x3iK052LZkm2GjrbD3sE+7yMYVYmaTFolBcJerfk7Zbn0OAzdQt3UmQJI9dJcEwDBH4UZwlY8gFnKhRPQQw==,iv:DSrfm3Efv1KYnqyi9iR4eOvpSD8wMvVYCZVZNhd7II0=,tag:OlxSdlNUepKP/uWpf4LCnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSDVxTjJoYlBJK1AzZm5E
            aWtaMmt2dmpVQW1tTEJZRkhxdkswWFJ2Y3h3CkREdWJycTNoc1ZwTDVwazZyVTkr
            dmdPeXFra1F2VmVtMEU2N0lTY3RYVzAKLS0tIHhwU3ZpR3UvRHBNOUpqZjdqdkJH
            Z1dVaExsalo5Y3BsdFk2bHhzdjRYbmsKp0JGWnuPzHEbC/n6MuOmRHKU1TIczFpi
            Do8JYlXDRA7WM9j+Os6vOOvYEN+mIixslDJv/HD1z8zYe8AKu3dqkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:12:05Z"
    mac: ENC[AES256_GCM,data:adbXjjxFb9Fd5waUfV8grUnwwjuZfxmvRvZb58oqrrQ0QbRREBP6fDG/q3zQ0M4XQs7fRHc7zR39Z5Lf2AvRuNfFXahAujsJ7odw8EWuSUKMulN6r1gDEi1RNqeTtooewG24f6gK3IEUDI4MWHyCumkIk6sz0YizS1UXWFq9Cp4=,iv:VkN6UqV+v7gFmJl7Q2vdwRAV9Di+tdCs1qoeM3308mQ=,tag:6XaFdyE5t7Nt9magOWrjIA==,type:str]
    version: 3.13.0
