apiVersion: v1
kind: Secret
metadata:
    name: teslamate-credentials
    namespace: teslamate
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:eesP/JZZrXUs4nrmUjFh6/FloNWlaqaEka6Z0AbwBDESCWeOxLWVAw==,iv:v/LoeFzUjUO9iM/kz2bGzzdYqumk/TD8O5YxnT21LS0=,tag:BMDs1KL/kPQSwIe7TclL0Q==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:T916qtFezlCdvoEj/cey8mIAAa32yNG/,iv:KvwVNPXZVHsXhdpaHvI2yVkKXT3tNAfLBpTm6runigA=,tag:WljNjyN7TigMf/V5HtXIBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcExlR0oyWUJyLzd3RjIx
            TnFOWWRnSktvYXVMTC9wcVNhNlZzUmt0bGlBClZwdjNiY3pCQVdRQm4xUTNWelJE
            WXhnbGFodHhIR3kzZ3oycFdlSnIzVjQKLS0tIFZxSjNRYWQxeGlsQ1FYUDU3NVk4
            ZDgxck5rT3MrVEpodGlsTERibmJvU28Ksf5Id/g7PE7oJSJgRGhJt4yDcTCmItHS
            4tGxncVXoE/4JOrZtoCIHw9rqDT7kbP25fCw8O6nCUiW+An5Ag5sPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-13T23:56:04Z"
    mac: ENC[AES256_GCM,data:OCXDKVvb/2ABdoLojr/di+PaHuhzbGGlcnCvRl9vOu36NHEphKzO2UENZAaHPFnxMwTDzJwrff+oBgr+u/5ILHZsqYzoFl0MZDQTvbwTwwqSseNlvhnOy1dOMMaMnUWxaoY7vGPpHHghxqowowrNLzPv/GltV5bq17VQOCO4NbQ=,iv:d33RpdXPGP705Y72XHJjIzqNFEHnIzMbly6j3rh+ZCw=,tag:EiuVpltD9gZfOuklLneLSw==,type:str]
    version: 3.13.0
