apiVersion: v1
kind: Service
metadata:
  name: teslamate
  namespace: teslamate
spec:
  type: ClusterIP
  selector:
    app: teslamate
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  type: ClusterIP
  selector:
    app: teslamate-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-grafana
  namespace: teslamate
spec:
  type: ClusterIP
  selector:
    app: teslamate-grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
