apiVersion: v1
kind: Secret
metadata:
    name: iptorrents-creds
    namespace: torrenting
type: Opaque
stringData:
    IPT_USERNAME: ENC[AES256_GCM,data:twpQ5Q==,iv:3tGXOG+XBFcq/D0d3CmtSpcUDt9xkJrNUnFL3X8cMvc=,tag:xWrNvNqhkWb9z7mfilRsPA==,type:str]
    IPT_PASSWORD: ENC[AES256_GCM,data:b5nSWdY9a7eXUkJ/N2jw,iv:VBcvq8c1sTufGHAb5K8WXLi+dsaLJKZH4CbIZ8hV9JU=,tag:xEuiCBU/18rRfj+h/i6IrQ==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT1czaG1sYVNWVElIZjJG
            L0o3NGs2U2FkOW90YkZPOHRnbWJHNmZNQ0FZCmkwYXRlWTE1bnIrazdtbmNLM0ZI
            L0FCV2NZcjBEWnA2SzltYldRSHpaV0EKLS0tIHV2QmhmWktXbWxTVGdsVzhJeVVY
            dW1oQTh1Zlplek5YOWVVaUMrWWZuMDAK2Eid6lneY84iChBi2RYLT4lSi7gN9zBZ
            h/9mR11WESj0+pLDlAbjxpkT2lJ3h9J8CNFmDgvoLBPFcpuu5DB9mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T23:36:57Z"
    mac: ENC[AES256_GCM,data:oIves0fXQY2i4pVN0Ijq3JyLEDJNTG1/aOFDUYepm7DTVU8kaDls7KkaghcVXECORt3XjowK+5o55Ck4xPSWls63BMDei3boU8SD69CQo5UKx+s4fooSaLCe8t5YI8d1gNOpQ/eKPQP+CJfHxQeXBk63ynDWRQ74Qn8nVdq8akw=,iv:oNIJwnq6/f7RkU0W8dxSJePQ7hjMR0ZB4A4NwjFd7Zc=,tag:0bUg+nKQEZK5D4wIRIcJnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
