apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: torrenting
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.10
  primaryUpdateMethod: switchover
  storage:
    size: 5Gi
    storageClass: longhorn
  affinity:
    nodeSelector:
      extensions.talos.dev/iscsi-tools: v0.2.0
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: postgres
      owner: arr_user
      secret:
        name: postgres-arr-credentials
      postInitSQL:
        - CREATE DATABASE prowlarr_main OWNER arr_user
        - CREATE DATABASE prowlarr_log OWNER arr_user
        - CREATE DATABASE radarr_main OWNER arr_user
        - CREATE DATABASE radarr_log OWNER arr_user
        - CREATE DATABASE sonarr_main OWNER arr_user
        - CREATE DATABASE sonarr_log OWNER arr_user
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
