apiVersion: v1
kind: Secret
metadata:
    name: postgres-arr-credentials
    namespace: torrenting
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:ePwGj8szqkxtEliSGb2wyUawJEaiyzg2VvT072R6MK4=,iv:VlaAqJxMWj1LR8u8KIXDRSzrHPVxnAGNCIQg9wzI+lM=,tag:UyCDNB1i49D93tWxYHVu9A==,type:str]
    arr-user-password: ENC[AES256_GCM,data:WBz7fcj5S4B+LxAmZBbJ5zJuZ3nMiZKGarknVzSjBgU=,iv:1mXpObjAmASo8dfD9siCOVhxdgll50s4YkLI137SuEo=,tag:AybgzIE3ya+HHYmme1x/cA==,type:str]
    username: ENC[AES256_GCM,data:6yri6BQ7XTo=,iv:fgbv5P+Ak3/NT/ykwhRb0l4EyvOYgIoUpOJKmAlQXvQ=,tag:L+7Ci8RxmzYET1k3zMWzwQ==,type:str]
    password: ENC[AES256_GCM,data:RLOqFrLdLG6gzMBNWgVogHQsiXvUMlBPQLpXcL1uBUA=,iv:U5K8w0KT6SMnnX67rPyxgiV7tNlM8HNvwp5VaYqXeZY=,tag:yI/yWGlAe4xosZ3OWT/dlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dktKNTZIQ0NQNXhRYVVr
            cVpscGxKakdadm5xREFMSlI5UTcvbEk3RTFFCmhrMXhrWTlFMExvZFhsNy8rdXUr
            M1BuVjNrREdJcTlBTmtaNXp4ZmJWcjgKLS0tIDdqSU8xaUhLWTFkQ25RNHdaWW05
            bDBwTmNUeGo3bGI2WHFwa1J3VExHWVkK1L1+gxRq30kYHsW+8t+mI7PxpyhfsUzL
            qM3XQEDG9TZzlR5yIiccbHuT7FgXRzslGqCjMBDamrCljpGqeo+6XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T06:43:56Z"
    mac: ENC[AES256_GCM,data:X4kFeIkcHuCdoTbcGD8b36NlKDd8kDfqwU2W6SbcwcdQjHJjDGiV/uyo7ye/e49ix9uU8jfYLNQSvMFSKsE8zAQM1alEH2Ll2fFv2e6Yk3yng5FO8oEyTIKtMZFy/t+XaVHR+eAwNvluGnJXwbhmpLVnCx2rTJw77cYTB4iTGX4=,iv:tEb5ehzpASd6BVQHcweDuv7FU9iJD/w2yGUzPmZ/MpQ=,tag:eWWqxxVa/LSDtdJatEmIJA==,type:str]
    version: 3.11.0
