apiVersion: v1
kind: Secret
metadata:
    name: postgres-arr-credentials
    namespace: torrenting
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:ePwGj8szqkxtEliSGb2wyUawJEaiyzg2VvT072R6MK4=,iv:VlaAqJxMWj1LR8u8KIXDRSzrHPVxnAGNCIQg9wzI+lM=,tag:UyCDNB1i49D93tWxYHVu9A==,type:str]
    arr-user-password: ENC[AES256_GCM,data:ZZKFHXk2z3UnCq+wWNF6MVJc9tsZNXWAU+WNILdjHrA=,iv:xHQLuaSjXcODx5yea8Pk1VsQjlHiBCJm7P26i3XTGus=,tag:Ks6/Rs3U5vs7fCBhKwhWAQ==,type:str]
    username: ENC[AES256_GCM,data:6yri6BQ7XTo=,iv:fgbv5P+Ak3/NT/ykwhRb0l4EyvOYgIoUpOJKmAlQXvQ=,tag:L+7Ci8RxmzYET1k3zMWzwQ==,type:str]
    password: ENC[AES256_GCM,data:G6Crlspw1exMYuz0jkHC7bla/o3d/ksT7NpCgAyFfAU=,iv:4G/gGTRRHjEWg1hCWWaTPjYVO16awUfNWyWYkUQvF4I=,tag:2CrgEAe1Z7WFg5D+K9RJ9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dktKNTZIQ0NQNXhRYVVr
            cVpscGxKakdadm5xREFMSlI5UTcvbEk3RTFFCmhrMXhrWTlFMExvZFhsNy8rdXUr
            M1BuVjNrREdJcTlBTmtaNXp4ZmJWcjgKLS0tIDdqSU8xaUhLWTFkQ25RNHdaWW05
            bDBwTmNUeGo3bGI2WHFwa1J3VExHWVkK1L1+gxRq30kYHsW+8t+mI7PxpyhfsUzL
            qM3XQEDG9TZzlR5yIiccbHuT7FgXRzslGqCjMBDamrCljpGqeo+6XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T06:30:48Z"
    mac: ENC[AES256_GCM,data:0suVGPqUUy+cyFlda5JhTGE/AGheQ7lwI6duZLVmUJugQmRa4L8xdLTTVlHf6yk1zLDLsXERRj6PuTxiBMq/qUDZO46QBkGU8TN5b2KK7unoSEfVlwFC40RS7RjzazZkhQ8F7lLsnzVgS9riY8iYsaj3jJ8n3sDQvISX507onXc=,iv:KP76b77ZIEs8+bIDZcclhNl/rYJGQiiWnM/tXgZHnys=,tag:59Cp03bMEbPm+Pp64Zlnrw==,type:str]
    version: 3.11.0
