apiVersion: v1
kind: Secret
metadata:
    name: postgres-arr-credentials
    namespace: torrenting
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:ePwGj8szqkxtEliSGb2wyUawJEaiyzg2VvT072R6MK4=,iv:VlaAqJxMWj1LR8u8KIXDRSzrHPVxnAGNCIQg9wzI+lM=,tag:UyCDNB1i49D93tWxYHVu9A==,type:str]
    arr-user-password: ENC[AES256_GCM,data:guBjVk16gxhT62Apksbifbw11v633U+YRhJyKnIjMZU=,iv:k0/xp/XThlbnKZXDi1mzqwj+c+zW/MdDXpJNRPuENiw=,tag:UB947Lh9/ZSIflzO9fvx1w==,type:str]
    username: ENC[AES256_GCM,data:6yri6BQ7XTo=,iv:fgbv5P+Ak3/NT/ykwhRb0l4EyvOYgIoUpOJKmAlQXvQ=,tag:L+7Ci8RxmzYET1k3zMWzwQ==,type:str]
    password: ENC[AES256_GCM,data:48l2gjrItT8UWirPTb31Nfk14/Nq/d8mP22+zoyYuxw=,iv:SRDC62aH2FwHOSMvhI53GCtv5KH3DyXFQsnGzEuz6nc=,tag:hHZZBcNxpuHdaXcXqjTJjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dktKNTZIQ0NQNXhRYVVr
            cVpscGxKakdadm5xREFMSlI5UTcvbEk3RTFFCmhrMXhrWTlFMExvZFhsNy8rdXUr
            M1BuVjNrREdJcTlBTmtaNXp4ZmJWcjgKLS0tIDdqSU8xaUhLWTFkQ25RNHdaWW05
            bDBwTmNUeGo3bGI2WHFwa1J3VExHWVkK1L1+gxRq30kYHsW+8t+mI7PxpyhfsUzL
            qM3XQEDG9TZzlR5yIiccbHuT7FgXRzslGqCjMBDamrCljpGqeo+6XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T01:52:16Z"
    mac: ENC[AES256_GCM,data:D4lzOlRWQ35mi5/tX53bUi72DNPVhQlamvOmAquCKeioFHROcQpVaunnM1pSIrd08epJyWjPuT/MrwRJZtlVFeo7EQz9oR9aZAHYN/DE9hPKIS31LshbUuE1ypKGzEvuwopV9PbGOApAEysmpRnv97tmSYDVDdqy3ruR09LXFRo=,iv:Em3VH9QCb39U0dyoXViPOuVilsc7f3ZueLIWSEvDgCM=,tag:4crvZ3alhe207NePQ7ldCw==,type:str]
    version: 3.11.0
