apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://releases.rancher.com/server-charts/stable
    chart: rancher
    targetRevision: 2.14.1
    helm:
      releaseName: rancher
      valueFiles:
        - $values/infrastructure/rancher/values.yaml
  - repoURL: https://github.com/saxocellphone/k8s-cluster.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
