apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: redis
      targetRevision: 20.3.0
      helm:
        releaseName: redis
        valueFiles:
          - $values/infrastructure/redis/values.yaml
    - repoURL: https://github.com/saxocellphone/k8s-cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
