apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: terraform-state
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:wczMa0bEJKEmZZ0kbj9tdpuCP6SqmBu3KaDPfZfwMWZuSibKqW7cwPvhj23ITfT0FigEIHM=,iv:WMMwlZ58qDFqWaqNUk2Z2CNvii7dB7wTJFq9/LlWd3M=,tag:rlHoX2vAR/sW0sO7RP/jIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtak8yT3czQndTck1aNHBS
            ZWw5Um12Z1JSQnZkNXNRK0ViNDAzNmNQemdvClVzbSt6NEJPYVorQ1Y1RHZFenpM
            QXNjQnA2aCtUTENMc25oUVF1Q2JQU28KLS0tIEdtMWpOa1lXSFZHc0RFUVlnTkg1
            cW1FNG1DS3MxZjZYQWZKbUN4QWV6R3MKKyGNiENIzBtFNrrFXrGhdD7UGAtomOg8
            3T1AUQIeeKZwN7JjRtAjXtCUELaGavKeScgoWWvmJf0DuJ+3cFX6UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T01:47:46Z"
    mac: ENC[AES256_GCM,data:OlFlBzHAhkDDehIWpiOE67NwcpiuVmOi7eRkN0SknnYqP/CgEhCMFM11BoSxW9d27xT+OSVzXjiONDzPMf2jMde2s75x+Bi2uogqqpuuUhyFKhtUpp2EaBbQE1t3UimxDBusCMGWBMZOQlQMe2oInyCQjoDMA0DF8ygUQ1hEuvA=,iv:kvQlPMLzLbl1sqHsyGs/qqtGdJlh4pp00i61suL/vnA=,tag:YgcxDZKr5uETsMw7sZ5kEw==,type:str]
    version: 3.13.0
