apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: terraform-state-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./proxmox-tokens-secret.yaml
