apiVersion: v1
kind: Secret
metadata:
    name: proxmox-tokens
    namespace: terraform-state
type: Opaque
stringData:
    TF_VAR_pve1_endpoint: ENC[AES256_GCM,data:VXvQOG02NQmG1Ht8UbwgzIxHYRCYxUPllrTF,iv:AZ9r+h7FSbGJ0PAzXvTFMalDEEUPiZc65hq9AYcThqY=,tag:WNLGFVtMKy3s9bErRZpNyg==,type:str]
    TF_VAR_pve1_api_token: ENC[AES256_GCM,data:obsXy+Z9p3QfzJmf6E4mn+h9uZs/IqVHKVjJrdi927mE61YpPx+IK/tmmbni8SHMN56hx89Mpg==,iv:Yd902f0r2T9vb6K6GViFUQWFN+8xt94NYgOHA4OGdWA=,tag:8K7H0NF8XLQEVUbildGANg==,type:str]
    TF_VAR_pve2_endpoint: ENC[AES256_GCM,data:YusZO6S9JjfjclLjdIVP3JG32Q9A0RQV0v/M,iv:FbHDTis4p0xvu63tDkdyVIUSgDom4Mn4jRspsQ+dRRU=,tag:iAGs1z7kPFJs1764jNs0aw==,type:str]
    TF_VAR_pve2_api_token: ENC[AES256_GCM,data:Zdz0O+YNC71jD3EWpadXYA9y4AcC5Qf8+Tw1QyCtfA6m+87VXM5rGh/zSiPXcWCyS8vLC89YKw==,iv:atHE/onYRYCos/YjcOEJs6yfE1qSfGdLlOwdls2Xrbs=,tag:A3uW32PKNyu/TB6Lk42ATQ==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcmxOWTBJTjZPRlRvV29k
            dFk2dWRqNS9rUWtCZ2tLSWU0K1ZQK2dxdEdFCkp5TU91WmdOaHdJVmt5MnpYcDQx
            bUpGWVljOGw1Sm5RUVlCR2lZUHJHbjQKLS0tIEFEVHNpRTF0Yi9nb293QStkRThQ
            Um1Kd20xcS8wcVBMNFAyNGdQekQ3ckkKe1Lah4QRypR0Tz1YxkR9SfDJ9ICWQaB6
            b6Pgvh9H6gFuzlAvMOlM4zydIptM60QpebvjJu4PYXNqV4fg7IRp/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T23:18:19Z"
    mac: ENC[AES256_GCM,data:VZrMupunDU9JWXtj0KEPKRyxzm0S4VtL51UdQNRWFfUhhEmdMK8+jUE3236AVP25uOVDxXrSJGyCR39qrzpnvrgappxu3GUGQ3JJ+KWG8cl8qIiiGqmCBBqj31S9xGTe3JPSOiPA1Qtp+fx/GLz0dRBk+x2umlr6AxvseWGElx4=,iv:ZGfnhMzCRQhd0/Kqw/g9FROACTKKfKiFPm0Ak128F54=,tag:yyeDH2VsUfUN+5IQM7baNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
