apiVersion: v1
kind: Secret
metadata:
    name: mam-credentials
    namespace: torrenting
type: Opaque
stringData:
    MAM_ID: ENC[AES256_GCM,data:GFO79MTjUiX0TCnXJjiqEp2rY9bOUsiRpPJItZGWngPX5zGLp9HL7GkhR0ibCAEnGyVcqNvdxiaTEy5106fqHVjPFCBsUD5OVhO5qZkeIvorKRXMJY4p1axdahDuG7yI8cYgz8EeYdQV8taY9a5U/WyzjvGp1ACNC8irCryGv1yfC+3ppUa+ad2iuQvK0AbOU2grcDCAbOntVSXo83gNQLKPEzO830j3bkUlShBXA1DAy5t4h3qHjP9pYt02ybGimB9AJp01gspMlJvruXEnEi2rbBqfoJ2m8Jl27/NbKQoci8P76gEkS4lPFEQZ6vY1Vjx7jz0ZEZQTks5Ht0KgRyGaxl3BEqMfzoiRHFL5UqLhxDNYwFvO99bpjRN3DrMM5e3b9w==,iv:0yrBglDcD6jrHQT+ToimnTfh5kJ5v+mKuppsW5px+TM=,tag:eRuS/VvRcxBnpIZS0/eDgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0FxazRMcTEzanoyK1Vz
            K2tvQ3VoaUExR21ULzZYTUFicWlvbUhkRGpzCkJoUzFEK0NBUTlEY0xQd212SC9x
            dUxxTFFUOU5oSzVlM0I1aUNWRmYvVlUKLS0tIGhmOHFqZ3ZoNjJqQU5QcEZBNkFn
            dmJ3Zk53SHdNZk9PRms1TjZSZDZlUlUKt89SBlb0rKS7umcW+fMTmDFBK69rr2U5
            Zut4C0aNH1ybPyt6PF6z7WfWthoYM7G6HgYxkDzodM8IKOMXnoum7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:37:08Z"
    mac: ENC[AES256_GCM,data:Ca1ww7dDrpspScqSQ7FcLEsxVLTUwyn3/g4SPNd2CtxEWp/OFn0hrQuBniZmPXeNkhowVD93s6XEjPQic16IUwA0vLEiWGYMRJsa13JSoGJS2rimm9TWo25bL0GDpOBzOCnqT+8dgcjtWmOnT0s6A9DrY6HAHLC3ikMDwQufUSM=,iv:hqYccPrJoZOOktgJjOpqIAqaI+4SOIb9hPkPI1P4RYk=,tag:jalVksqY/4DJkEJzxXe7IA==,type:str]
    version: 3.13.0
