apiVersion: v1
kind: Secret
metadata:
    name: mam-credentials
    namespace: torrenting
type: Opaque
stringData:
    MAM_ID: ENC[AES256_GCM,data:waJhVFUeGZ5W4Si4NhzoPcUxJ7VKmnfFYSPszRF9bItA51xdyIbfFsOUHIAR+M4ra2TKMhnGyZx1ocAirG59sGgARJ+McENMie1eNNN/OsA7BQlFjfcpjK/dUMRtbo58vccXkcv809GCTU/w7x3H/7baCYpnXvooI1u++JAtLhdaWnztrQW/1JHwxru6HcwjcVGrBIIY+SnXwnsnkRL5icwoBrbs+xBIL+uEF4/m1JUVJIylaAP7qMgZWTSLQfY6ZDEvWlxDxgwVW4YV74oy/KE3BjBgc+84mZgwxuZWr0tRUnsexobeRUGhHerDJQ1+lR4cLieplJZRJusoMyodoaSnZcWktsVKZEKigJSKdEBYnh52/Xu4LbNS09hOReqahDVQAg==,iv:KvkZAyrKWJoo4EWxy0ypXDV54W+cu5nlg1UhD6PH3GY=,tag:4X5807kc9ixui+8Un7GfwA==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V3IwcGYxUzJBT0F1WUp5
            RGphS3BLbzlhQ05HU01VM0hlZEoyTU8waXd3CkVVYWhVMk8vWUNZRE9KK1hVdUZn
            TnVRcElTVXI3NHJFc1VGWGFFS2NJZ1kKLS0tIC9oOU5sQXFsenlaK0FIY2hsV21s
            Z2t2RnM2Q2J0OTBWcGhpTllURm5mVlEKtEGeL/j6R//xzOfREYyFUCiABJx15CEm
            QBKOE2BK4kMqxRovgWcCEn567AVQUSFWo8V0/u4gdnAplnsKzBbLVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:30:36Z"
    mac: ENC[AES256_GCM,data:g1lZt/klviaWx3dhiFX7sNM9zPxVTKPgL+aU6NbSdQ4IvOHwrc8I7mEiJLAdEwKd5wq9dmfueSRwkljy6ExwlQNBwFr9NPMd2CiYKZXUOvM+SZXtm1WLDZg+11W5JUz+dpMhSbijYd01K3hoLqpW64NIiiwQctIQK+nTgjBQ50g=,iv:umzmbnSUWAIsdzrRr8RHxLmdlA2zlg5wc2+RfWhlD98=,tag:oeyq6pVq+CTGMfvuRw9VmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
