apiVersion: v1
kind: Secret
metadata:
    name: mam-credentials
    namespace: torrenting
type: Opaque
stringData:
    MAM_ID: ENC[AES256_GCM,data:DquhANGqXix59PHJkVOCKbgrnU5Gw8sQIG3vZEnmcUsTaJBzYxrpbV/yVKA3d/bXwcXHciv4RBWgeK1AjWcTRdybh0Qemcb+mxYm8y+NIB6eMlUtGxPmwn26hl2OcpCW/A41Qj8v2DPKyCh5wb+xwLV3EHrQZj4iER6nXIDnqEaMUMPjrYXhYTW9VFCM1m2eGFGBjhMGhDdEt9oatCf9QkKoJowMyjK3//yZBuy7/ylj6qKaPgfWCyymYASGI8c+BYK6Yo0KK3dtNFoTKGa4TXSb1Lpo7AMcjt3reN6mBsvbstv1xwaLnjllTfxZXyoJp70PTrUXzTeF9sHSJcQ5lCTbPDxXUrtTpSM8FDyczFgD4nqAbYi7/10xkpwNs4Hwr56w1g==,iv:1m+zrXG6Py64YhquxFFFGOSIJ7Gxi2FcfzIpod3w6Is=,tag:4NToJVQtRo9incjS41efvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V3IwcGYxUzJBT0F1WUp5
            RGphS3BLbzlhQ05HU01VM0hlZEoyTU8waXd3CkVVYWhVMk8vWUNZRE9KK1hVdUZn
            TnVRcElTVXI3NHJFc1VGWGFFS2NJZ1kKLS0tIC9oOU5sQXFsenlaK0FIY2hsV21s
            Z2t2RnM2Q2J0OTBWcGhpTllURm5mVlEKtEGeL/j6R//xzOfREYyFUCiABJx15CEm
            QBKOE2BK4kMqxRovgWcCEn567AVQUSFWo8V0/u4gdnAplnsKzBbLVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:55:08Z"
    mac: ENC[AES256_GCM,data:Mw2NCvOMfyA0JjyBWMUhMNkh3ard7Jh4ujuhh25r2dIxUKsw7DXqmxE0OPB3tUGRihNzMVhzFPO+gbUPPXdBi82i5B3MwmVI2KULCWvZcdzl8kUSNfQd3vKRkcS3Lkg7I2O5ztS/YQrSqjZYbGvrsAAagUww6d7/icmElO4uX6I=,iv:DGsa8EQG7e58Jza1yOW8n+aGwvKo730ytgxRVYe23+U=,tag:RTbrr+AdCBl5N4OGoF5vVw==,type:str]
    version: 3.13.0
