apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-classes.yaml
  - openhands-runtime-storageclass.yaml
  - persistent-volumes.yaml
  - rbac.yaml
  - coredns-affinity.yaml
