apiVersion: v1
kind: Secret
metadata:
    name: google-drive-rclone
    namespace: torrenting
type: Opaque
stringData:
    rclone.conf: ENC[AES256_GCM,data:TER6/QxT0P0x8RPqsstl8ak/WVXDN8AkyIEOh3OUKtwFW2iSVnZtPT1GnNxMKaR/t/8Z7JcAibDybaJEEJ6QfD4jSg7v6pr0UXbuxJjZmTyQbVgnn4gbUHk/8YxkFjC930S/pPnR9ALwVfquxKAPOjRTTRtASsp7nb0S9Fgzvmcb4jCnIkoU508TVJpQLrD4dr1n2YnkCQY9rTdkpiKwnZtOjXzBbMntOtW/RbQJBXEm03O/zjbwMMaaNdBNS1rMT/+mOeE393vTAuQ82rcCWRbEritnxI7OkFfQo/AJNcl8G5acg87CHZGkkeOuln50tTNtXAaCmPVeThsgkOrAiXEUGquzjBtWXMyY+OSleBK+xefFaNZC/Ja0wD8o6FsXdbSYxbMvkGuHdvfBmjC1vYeuovS1F0QiHxlMkcKLUqZ2Yc9QtXTcTF39JpDy1/VwupYUM1ETbb83VeY3qyqs61Du619Gs4BWV1/G3bmoVf2O01TMghSee+oZrQaiF90ZCC7ri77PvEekYNP8nNrOUWydz6zV+lnz+YlrSQ7sghaUH/lx8cxUFdub/JD1c7jfrb/CTCu13kK2vStYZhroQSZTXibR0SV0b8q/ikoJ70XUwChLXBRymUY0QtPZ95sgD97eVccnGr+anCU4g+N6wGagcBVKvTUKD/FWSOdVDdU1x4bN2slhbOThoJMK/emxyGQMNeXE33g=,iv:Os2mSuXU/tl2VNkWIHuhRb1clv3G7TvMFFqZ8xQse0I=,tag:ds2yugps6GgGZn0lxmtEew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOU9lenI4NCt5eGUwNzRw
            dERhVHIzdHlIbVc3N1FhZjVjZVVqYXNWVlJvCjRWMTFiVDh4VFJNc3pGUDM5Z1Y0
            K3V1ZWFrZ1lGNjFyNExwNjMrQjRzVGMKLS0tIGtuU0Z4WUh4ZG1HNDJkdFdVNmU1
            eVN5NDU0OXk5ckRHa0RUSXF3TzBUZUEK7XnRAI9gZoE0rqWcOKmo9xCc/xQme/Z7
            Ir80OaXzC5MhwBMnTQt/EmWQsCCyj+LqQx+HA+Y5Xlfd25z6rvuc6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T03:49:32Z"
    mac: ENC[AES256_GCM,data:/MNr15nRsV+SlE8tbofxSpXHwmt9uKW7rr7x45eBqNN13fLtq6McIgj5lWOWlh4EHn/qPK3CmY20+eRgZlpruO/PTnIX4Oh+yfO5BmIa/4mCdAK2lEpTIPsZnxPj+bRXu0kVg35Oht0GP783IOt3QB0vOLkEQzbFmdWCh9nydtw=,iv:9doJJFGhF6WKOz65t2l7NwI7h9oVJd4sXnY+wT44TJM=,tag:/ZAMc867U1dEJCyzyvHysA==,type:str]
    version: 3.13.0
