apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services.yaml
  - ingress.yaml
  - qbittorrent/statefulset.yaml
  - qbittorrent/service-headless.yaml
  - qbittorrent/configmap.yaml
  - postgres/statefulset.yaml
  - prowlarr/deployment.yaml
  - radarr/deployment.yaml
  - sonarr/deployment.yaml
  - readarr/deployment.yaml
  - flaresolverr/deployment.yaml
  - audiobookshelf/deployment.yaml
  - bootstrap/configmap.yaml
  - buildarr/wire-dl-clients-cronjob.yaml
  - iptorrents/cookie-refresh-cronjob.yaml

generators:
  - qbittorrent/secret-generator.yaml
  - postgres/secret-generator.yaml
  - bootstrap/secret-generator.yaml
  - iptorrents/secret-generator.yaml
