apiVersion: v1
kind: Secret
metadata:
    name: platform-postgres-credentials
    namespace: torrenting
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Ro3WYBZr0f9ZNZVHm2a6dO64OSeW9eSi+tomaxUVeG8=,iv:1GKYSQyg0Q8DaUUkkhx+xv+HO11qHNxyCXolfjpG3/0=,tag:UuEogPi0sZciBXFRXhm6IQ==,type:str]
    arr-user-password: ENC[AES256_GCM,data:4n6gzJ+nnZcq/l3SQHOI0wfq5UOYV+TsYRMP1KCKDUc=,iv:QdxI4Ykd1GnS0yPyf1mV75YGgVNM1tet3sjKB4LQaxA=,tag:b/pNuohtBUuj5xyMEseAZQ==,type:str]
    username: ENC[AES256_GCM,data:ppiOFDEPIeI=,iv:p9hdeIWj8PFCAWmPotwkgCpsQsXl37kbIKKPuhRkFao=,tag:NHplWB8NOFmd1YjPxheC/A==,type:str]
    password: ENC[AES256_GCM,data:X0l2Uh6q27PLBsHueKX35Yrg9fDYpkqXozEaT9pD/Eo=,iv:lZuY4MvQ4UWUi8qQEnj5Mk/sqz51pbCtaTPocUye3JA=,tag:yiSGuCqGrja8ergQ9G97Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOVROaUVKL0JpNzVEWnYz
            SldiUVJwTEdtS0UvUVRLR2VaUERqTTVkU3hjCit4cnUxVjRWdGhsNVlVaU0wcGpY
            RG12Q3ZsL0huQ1RqOTYvWVZmVEkvcmsKLS0tIGx1cFQwWmVITlZTVlBaeXlFMnAr
            VFRlZk1TQXJseDllakRPREdIK3JZbFEKsLAy2rNii/WtUccCBKFjH486n/fr4zEB
            gnQYY9XDHKTm41trojuAMvMM3QjucczVV1weSZURohwz1ZgUzp/vCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T07:02:10Z"
    mac: ENC[AES256_GCM,data:SX937kbsp+RihsIKbbQUnTWN9BhYuDhCFd/MVQqear6IQDbwqfR7BnoTeENIF9FY1995C78EAIg/ZQ6+jUub05LZ8lksrqKv2ABq0eLaribaaW28iqe+0DjhOFpbBgJbR0VjHAxM4a7Kjue5YwmqtqjvLbEZT/9QOiVwc56c7YI=,iv:S6zsmIAlGRPQTSVHGZiQhJ1olOcTms5qiXzPc2eNRoQ=,tag:CfUln8YO0YvrJIhyoQu/ng==,type:str]
    version: 3.13.0
