apiVersion: v1
kind: Secret
metadata:
    name: alert-responder-telegram
    namespace: monitoring
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:wIBZOmuD7Gm/eSOkxiLnQKAGvyctH6oS0JZJsXX9CPk4HLTPPlu3r/vePhoWeQ==,iv:hAy17zdX5xyNIrRsckbEDlEZP2u/9ANc5qotoqcDx7I=,tag:C7Q7l7kyd6+MplTgdmGSeQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:B3q5XEh8Yh70Fg==,iv:9ODYBaxPkvFTnoZa+WlTfefdBw1KmXK781oCGIAjUIU=,tag:NLrmTPzFMuIU75X0HjM/9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZnhOcGNyUEt0Y2NiUDhn
            L3ZoMndra0FHcWFnNzhNcGR6aUhMSVRJaXg0CjI1VVNVNEwxOWZLYmhaSDlRVDdq
            NHlweW8ranRHN3FDeXg2ZEExbkRYblkKLS0tIEN6TmhjdUtnSlc1WllPd2dmQTN2
            TlVOMFF4MkcySUIrbDVqMVUxQzBPN2MKu99SVXcKkg2BOyw6kuj74F1ytbQ23gNS
            MR08e0Qg/AKkM28CILxsWTkCpSbf5Wt9SuiSnCR4VYVuWj1ytKYmhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T02:56:01Z"
    mac: ENC[AES256_GCM,data:YCta87o64+hW3uqXJZ/htk9ylKc1KDpiK3CRPlsF0V1Uc3dqp6VkuOuJBJrUUQtnuxgh+Sw0F3qwnUMgVld1P5Zna3Ta/AlzoegPQsjLMpRuzUuRrofxL8WnqVSg9gDgyqjUqhWkGd8vUwzmzWqqm7nsfTv7sq+JHnPCnfcNnLg=,iv:jkJJTU+bEw7EMhhTfdlUwOsHtmOiXxxN5iC5efMOslk=,tag:J9POG1lJumcuy3nmfUnKKQ==,type:str]
    version: 3.13.0
