apiVersion: v1
kind: Secret
metadata:
    name: alert-responder-telegram
    namespace: monitoring
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:e7zfxci5L+ZJPbdaIvl3j/0Cb7a9AaVjpdk0Cx4FJCzntIdYTI5B8OmD7UPWqw==,iv:UeiDK8YR03gocW7Q7IIKpWpIIzoC7Y0YYdeIOJ3Fj9k=,tag:pbla8xaHvf06VE2FUfyrKw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:uGwICd2sVIMBpg==,iv:1kWlOJatG4GkbNmyWA1sUtW6tjhxHUznJOBEquKZvQ8=,tag:BZhHWS6UTztapgPQmFGg3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcVpKQUxnZ3o3TkZZQy9o
            M0lCSzNVbzZTZ2NMTmFpVlI3T3NxRFd0S0dRCjcrYmVhT1dYU2pRekdWOUNaQjNo
            VGNuTE4zdGFWdVQrUHd2RC9ZcWNpSjQKLS0tIDFOTlRpd3ZKQkFxSmllN3lLbks2
            SG1QYlZ5VnpVOEZqT0thS3Y5b1dTTUUK819kxlJV515LxXoHfu8Hmm+8xu0dYFtX
            cEIxdOTH7a6grsBCg3wWZpysBUkD4zTR9ut6oL2IfXueYHdoKInKFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T03:07:10Z"
    mac: ENC[AES256_GCM,data:xZGUfx99OVX0EWsV91MOXcKvcdjnTZRyVP/+yzeUhfmkIOUDPHGZWhUDA9znnbyw4HwSYkHDINE8pBkO5nU3GssHL5hGd+v72P+0zMxxwOHoruOIeUFchM4EZtoylK+n1ezgvmqCtpES/X+yg2bUqm+kOXxjM2/7NKCNb+CBSi4=,iv:tOxgw5r8+3hrM3us3qKvJVSQr99uiY6QiYd78hDUzLM=,tag:KjhPPXZxocYgdiWAWSpiYA==,type:str]
    version: 3.13.0
