apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: alert-responder-telegram-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./alert-responder-secret.yaml
