apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:XdMk2bA=,iv:qydATfifrWpc08WSMEGYv1Hmn4VVrc6zWnTAt966h5s=,tag:Jr6yFSKKfYe0HNk7ALWKBg==,type:str]
    admin-password: ENC[AES256_GCM,data:VRKyqYf88LxsGldMepd/FsVg3DWOIqt4jkY6rYjsPtBZBdpCKG7N4g==,iv:7xqMwkSnOQICtv5jjzLis/Hf4L04KXwZtbCvmb6C7TY=,tag:YRmrgIunHM7glh807umI8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNnNFaTJCSjZpM0d1RlI0
            UVVQTlVrQjVvMEtMQ0lXSXdZOVI0R3hUWWd3ClZBYklWaTgrdzBZalNXUkx0a0RD
            eEhqYkVZQ0hKakNqckxJOEVrV2lPRzAKLS0tIDl0QldMWkhHaFJtNmdRZmY1UEl4
            eUFpb3dwSGhIR3luNVdhK3lLd09SQmcKiwBFKbp5wWhYFvRc07jJtXVet9F5tVJo
            BFnDiP0m9hpG/oDc6NEKVuv08jeWSVEeQSij9ECDu+8/vALjsDoROw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T02:18:07Z"
    mac: ENC[AES256_GCM,data:DMqx209WWbaX2B9IIL8jzVUc+HAW+hyyFuHVqOUJtojs4wA/lU47G/2axbf8g57ZVl+gUUyDSHd9uywPifKndRO08lhrFixhKOruhj7U+c4tjsDIS8mjk25icO/+wCAd5ZRZxBhDki5xOYRQ4GL932RgryFiPlXSPeynYRrKG7E=,iv:TPzmlwf9fgnrtQgzId4+vdMq58Pe/DQS84U97BP2694=,tag:uXB8jgn2i+vOnESGev2BSw==,type:str]
    version: 3.13.0
