apiVersion: v1
kind: Secret
metadata:
    name: grokbot-webhook
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:FlKo1pov+6b88ozXXnzFtf8bMuqxX6jNidgBf6biiybtW+0bq5xEJbgV1UaNLPu6VY0/NrGzpyWNBAehCZDk0KJtqFHy,iv:vw1ieOYXB8T1aC7dd10htdtLn8DESzloCCyYWL1cNow=,tag:tIwBVqgmNORMO6999pQ6bQ==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcS92d2dERUJnNStEM2Er
            eTBCUnhvTys3SjNDQnNzR1BmZ2J4bEVSSm1FCitRVlBzS3B5S2Q5bEcxUEd6cmVN
            QnZFLzBnNGRSMG1wZjd4RTFoSEhaOGsKLS0tIE4wWXQ4TFN5OHIreEw0blJhTDVY
            YkRzNFJtMW1ZZVZVcG9GUXdVMFhVREUK2nFQfJeVVferMScb6K48Z9YV6ZRShMqW
            qDrxf54xS2jrXJZHvW/DUpL1tNBrkYJaKIzkxDZck4R83Vox3Hu+0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T19:14:02Z"
    mac: ENC[AES256_GCM,data:YH5Xk/8xy47h5N9JU4qfa9jTjAHWgxsYjN1L2ZuWCapgzY75EGwxiivyHnRT6PriAogY8MvMvQIiAzOl95VMGl7ymDEgrbmUBYu6MReFuxUFhFXt7ROVquytQ4TkRBEHNSmlwot0BdCb9mj1xod35YedSRJmJpRbEpVhT+lf32M=,iv:0rJ944ZQubBCJpVJI7bnwh9IcjTjt8Hi6maayb9stL8=,tag:46PyQ6Mj+7J8zV7j2hbqpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
