apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
  namespace: ai-inference
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-output
  namespace: ai-inference
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi
