apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models
  namespace: ai-inference
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 220Gi
