apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rotki-ingress
  namespace: rotki
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  - host: rotki.k8s.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rotki
            port:
              number: 80
