apiVersion: v1
kind: Secret
metadata:
    name: coturn-credentials
    namespace: coturn
type: Opaque
stringData:
    TURN_USER: ENC[AES256_GCM,data:SkHQcgUZgMM=,iv:56IwrAdfKrXnaO5gS+ZwHXwQP2exr4xhjfFup1Iv0/k=,tag:1gLSfbvKy+NfTbLzs+OKsw==,type:str]
    TURN_PASSWORD: ENC[AES256_GCM,data:UMYEXCzCyf3QYY3Jpz0CtJlIcGFoZyqCc3bI6z0i,iv:3Q8oMFTgocUMyH/Q0sVC7SY2pzoHUS34+ur1wyDUb0M=,tag:AEgwsLry9AIoiTdk08kZAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWpUdGFlcGtSUGhzTDUw
            TUFRMERSVFVpc0dtdlNqTTZRSENoNzV0T0R3CmJDblNHcm9VdlEwd1JXRWRLNWxS
            eXl2Rzg4Nyt2TWFyOWNtRG5lbGN6cmcKLS0tIGc2d0xrbVp0N25OT2RPV1p0c3Vi
            V0l4WEczd0dYRjRlaEh0ZkZvR1ZCQVkK0f6F+up8pMIh4tt0jz45wr+87aJVfZyq
            UbvjWrrj5FaiXRSecX6TINbfMfYqhfoetblI156X3kJMzjXpwETy5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-13T21:33:50Z"
    mac: ENC[AES256_GCM,data:4HE2aB9qiV5TnNM0q1YgZWMqyL4bX30RF3AizreSsfAqW17cbnID/rvoOLOxiP8HbUAbXr1pGYKAVBBkkIHHSmvnVMUN38KWjSFs+4aSRHEHdJXc66xjhWg4Y72OqZWMO1sNNeNyg7CAkaezgXuv5/rRMzgRSwzhlqCV3qerqSc=,iv:q1gGPArz3DyleVZGfLXOZoSIPytqeUGCmya2Sc9SLhY=,tag:KB1YCyQOWIyIThoJhO0DCw==,type:str]
    version: 3.13.0
