apiVersion: v1
kind: Secret
metadata:
    name: clipcascade-secrets
    namespace: clipcascade
type: Opaque
stringData:
    CC_SERVER_DB_PASSWORD: ENC[AES256_GCM,data:6hT8kgLfXA/sKTaq6qfChuyxERkE1m6tbpw7ZmBnM5l8ecDcTpwxk2NBu5E=,iv:6OEMAZOWW/EcACy9cQTo4y4Q0sWf2OTircIKvI6aKKs=,tag:oENQEghro9yV9mBN0UYjag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZWRLcldPYW5pMTZia2ZU
            MTZLa0ZZYjNEVTRaMDR0OVdWanFneWtkaXhRCnYrUTR6WmhMWEc4czlORU5sUUZQ
            TFhMRFN6ZmtvcTREZHlDTWNCd2c0MWsKLS0tIGMvb28rT2dwTDNjcStxZGJZVy9Z
            citxWlMwekNNYWtOczVRL3hUZzdBcHcKTlhGTWLjOy0q+mspsXSuCytVNNfz6eV2
            8fNUeQ81PVB5DUxEdkpon/fm01nqha230E3hZ46bYlH9ZQpC5/3klw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T00:30:59Z"
    mac: ENC[AES256_GCM,data:moQ35MxePGaM4U8uKji2HpoU7uHvj/tNj/7HOalCVo8szgZNRvLuZ/jPdeeMg5rYR1EiLtl4YZRhPM7F2Xjg70+EuDoS/syF7BhLoseo1YQD4RvoqZOqY0grwYdqeakwGbFBRtn98V17TgC/ygB8HdUR1Bm7DlgmdZfdgYnFyIQ=,iv:0n0M6Zsk7qVzST7qvDdEYLFO4q1ll5D/UCZf/xGtGTk=,tag:CcL+cZ0KHSMStB/hjroBxQ==,type:str]
    version: 3.13.0
