apiVersion: v1
kind: Secret
metadata:
    name: clipcascade-secrets
    namespace: clipcascade
type: Opaque
stringData:
    #ENC[AES256_GCM,data:o1+32cnLGOMTHuSDhKfW61zd50NJ0JXKntPuOht6ldrUr/dtffknUvNFxGBj+Mtcyi3IDEcvt/YAfJsIou4Vw0l8OwFm,iv:pQObADctAqiwTVERBaY43NX1cRs39bywZrKRQbvEzRk=,tag:/M8ssi40sBQcDFxXL6oMQQ==,type:comment]
    #ENC[AES256_GCM,data:K6VkQR78qmbi9P+OfZ4fZQLLXMPVlHssF0jQd8o+CwB3c4MOeR+3hbhEqZUfd57+D7jA28xSE6Jit1zU7IM=,iv:k5cMKUFFRdV9sGq7ZMhOJ4vkKDm/Tb+ldgsOzOS/YLU=,tag:INe9Xe/lsjqUbV77GCN5Bw==,type:comment]
    #ENC[AES256_GCM,data:DNuRr7mBvfkEpGOQqkvVPEsyK65TnHTwVgIseheUButtGrfyd0lIzFXj0+yhFCpl4i89xS2xIBZhf/iP/6nQLA==,iv:ujaEAuG39g3DWhQ+I1RC3vcrYkU5mqJHbjfPSfbb+sI=,tag:Q9Fgn3WMQANvF9e1B9farA==,type:comment]
    CC_SERVER_DB_PASSWORD: ENC[AES256_GCM,data:I0wEMiExvPoDtFVYTAr923UVq3s2ox7fHQlGRiH9Ty/Sr+6uTlmR3MwWa0vQMFq/xg==,iv:mmaYCsgSJd7KpchcYwLrMP8yxv3QJeizL+z5Eb+TJsU=,tag:rlK6PN0kz/acujwh4ZdZkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTlhNZTQ2OVpCdS9UeHRr
            R3h2TEw2VHA0aDI4dWsrZXVzaUlQNWQwYVI4CmU5TmF5TFRtTkpWSWdoTS9DTXVz
            YTkxSjFSTjByTkNLWVFibW5ZNy9RcG8KLS0tIFJWNkdjdUlzTTFQNnJoZzdmZUNw
            NFNERFdwb2hvZ3hGb1RMTVlUSVMvdGMK1dh4nkWgXywO3ABQIiI8fcuoG74INVJj
            ciKcmGKbM5C5WDkTnDekRcSLeyDuJCPTUMP43yiQ/PIc7DptRBv1AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T00:36:22Z"
    mac: ENC[AES256_GCM,data:4FywBM27bMnSpRsN7oFrypT1vx1GakFXWrQWzz7XV2dY5cBJFhgw1x6juT7CkDYgd0QaBux7TedTMwm8BNF00/xKpDzoWt9aM0UgkWJdEv2mwLo2LEQC3JFIR5wDaR7oakHts1tkBOncBwiQq4AcOTiAUvvAqsm+f2Dx5bKZnLI=,iv:+mv/nbKnEqzs5/h5zYkArHDSC474jlgP9kKk/cSIXZs=,tag:imV6etfPIFXaq/IbBS1daA==,type:str]
    version: 3.13.0
