apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-workspace.yaml
  - pvc-docker.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - configmap-opencode-json.yaml

generators:
  - secret-generator.yaml
