apiVersion: v1
kind: Secret
metadata:
    name: opencode-secrets
    namespace: opencode
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    XAI_API_KEY: ENC[AES256_GCM,data:L9VK9f8LLVvX/g2c5Ll/3C2L/pHH3n2QLSZBTRFaMgxrJvpAM4DP/KFGjUKJHheKxcS6ieib0I/CDi3NCtJg/kVWzakpTq9H665G2o+NMf3rVPLp,iv:J5U8Ry1TGdlFJzgeUZub9v0sucErGewWGBPC3Sq7hBQ=,tag:CMkYRPYZOQMS3YPeCNgimw==,type:str]
    GITHUB_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVpSbkV2MEdPQ0d1WElO
            dkJoYytrdHBWRmFjWG5XUWVVcFptYTlGdmgwClQwODZwMFMzTUhQQjYzYjdGeE5D
            b05WY1dBNG83ck1nWmFBMUdTTitPdFEKLS0tIEpPT09POEVOM2trR01mdFEySFo2
            WTcxbFc5R0d6YStGdGxHbUpKVWdwOHcKUTFBVb44dz8kHmT/RrqEmS4lMhJp0xuy
            pyZyDlBTuGQQVuzB+Q5eQ52fpW6OQ4OHn80qobClCxDc5B/JcF7Dgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T23:42:30Z"
    mac: ENC[AES256_GCM,data:/Wb+BRcQysAazTGqg68rpt2lnQWO/S4N19KI4q+Nt8iGOwHKJBDgrUP+YbcbcjRKKkBit3RU8Tr3A+rDPXi465zUXwUxspDeiZCjj/BjPpCArUaQq3V/vUKOQClGOCEHQH/vBDIL/HOFvcu8w3Kk76zKbj/Z2fEXG2kuNPkFdmE=,iv:P7IjuyPQZZQMnKZmEYwJwKYjL1Mv1cU+JMSA0N0Rwho=,tag:lsr9JSQNr6Zrk+xhr5DUkA==,type:str]
    version: 3.13.0
