apiVersion: v1
kind: Secret
metadata:
    name: opencode-secrets
    namespace: opencode
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    XAI_API_KEY: ENC[AES256_GCM,data:siOhQ7GLtByni4+jgzsT8/Rjc9se5qlvNM4gksA42YXuC33Ialttlk3oVI9EmBBK/9li7QQVlGFHPITkV/REuIBGDkzenr9c1UU6PmbiaQja4iLV,iv:JjdYxa9Py3Twecjc1ntJ+owvlKGl1YJelSMIFlKefsA=,tag:YuuVQvXHNfBC+og7TmeSjw==,type:str]
    GITHUB_MCP_TOKEN: ENC[AES256_GCM,data:Pu7mrci/YvHl1qIBtkBF4HboP4kHZ9v7qI9X4m18l51MkhKIWPV6PoZ6zDpYZXndObXisUZTIywEeT8LT4vnwQ==,iv:fmRIvBT9rwjQWlHpBAXlsbTG6m3s9mUNTeHLPLVZLPQ=,tag:vFbHwKSzsTHF25VGLhNtZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPalg2Q3JGRUM1ZklsdHZZ
            SGErbFE5U0p5Yy9VRWRMZVI1TmNsSCt0K2dvClFNZTU0cXJPNXlCWFBwS3luTElG
            VWR3c0NRd1ZqUzUwSWVPMTlPUGhSL2cKLS0tIFRLVytLdjA4UHVvUnRxeHRxRkRU
            eVhUclI3K25zSEplWVlVUFBlMVRXdGcKqkHqxZssqz5oeDCaMqBxqKyNaF20O8CX
            gkfJiYGiDRL2DjV5JaxLDIiyikrWahKEeVhbg/7Acbt6S+FyHFhIGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T23:55:55Z"
    mac: ENC[AES256_GCM,data:W2Y09LN77JdNbLXcLk+JgVfMb1QGD8HpPebHVP6x2iGdE49bokpqFPSq/WWv0L4WKjhIxXblERFbddJngXBKWz/LLXG3tPdn1oCVdWTIYHQGTDva+aVTWv07t/q90yyL8SeN4qvwsGy0vvDjTdFKrZmqQm/hmdCMaijSZfc6odk=,iv:2PbCT2vGgeUhsyreEIba5bE7/qwGTwUYA1qBXxthO0Q=,tag:a/jIYarxjv58axYo0RJjTQ==,type:str]
    version: 3.13.0
