apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saxocellphone/k8s-cluster.git
    targetRevision: main
    path: apps/ai-inference
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-inference
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: llm
      namespace: ai-inference
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: comfyui
      namespace: ai-inference
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
