apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirotalkc2c
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saxocellphone/k8s-cluster.git
    targetRevision: main
    path: apps/mirotalkc2c
  destination:
    server: https://kubernetes.default.svc
    namespace: mirotalkc2c
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
