apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
    namespace: openhands
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:mU07FT7HDo/udZ+4uF0Oj81qqHHCyY4uMpgOWJBUcCDD1vlitQGokKQb6Ng+tIqZGxFztqYvE68xm8+ISaeFQQ==,iv:IC+B9TErCoKpQlppdWGsOvXerhFTEGdAriyVo3pDi30=,tag:7Kv2Ndchy2UZc2SXPbSfvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-realm
    namespace: openhands
type: Opaque
stringData:
    realm-name: ENC[AES256_GCM,data:hjmSDdFYS7w=,iv:/FWmX4dr1biYbysbL6f6f6gomRETkYmIf5TADE5ny7Q=,tag:7eunEVMONFhaFxRmDhFhnQ==,type:str]
    server-url: ENC[AES256_GCM,data:kqbXQXYtEURnx3K3XxHw,iv:tCsH58MPqlS/O8d8K1fzkKUJueomrdMm58oQGLo9B7I=,tag:RQmm4fSe/07FFld1HCrAdg==,type:str]
    client-id: ENC[AES256_GCM,data:IB9yw3x/XhA=,iv:TIm4OqPddeQFnbtPALukJsbGEifjOjYe7jYISOQc7CU=,tag:I2ZB7t5Uuf079cLpvjvibw==,type:str]
    client-secret: ENC[AES256_GCM,data:LQoybARRQ0IwzqN4X3ITR9mjEoJR036V/BClcvk7oNZoOUyYSgMTTdiA0SwoGiFNKCYtAUAkfU73wrFJwY1caA==,iv:zeNh11oTK2wVnx0dgGX5cVxaJknXtztYQgndbSAH6Pk=,tag:zpWkV/tsIySU4oTEhlhZMQ==,type:str]
    smtp-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:wr3ncT/0HqpMIo8NZfoeI7KKveyD1oKWmW9BTvXs7xkMWqnopdrHUif5dRJ9zKOlSzumsK0h9jyWOSRcGkSupg==,iv:ncETJ4ENw/LAskdlHOHoebYd2i2V4Rq4kw+68siAuII=,tag:HPsEBO2f2+EUYYnXrLxyjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: openhands
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uv/SsykccIKs,iv:nQlZvrYcllwfYc2MC4gmLNPqykMMEUUDJwPK2A1iGkA=,tag:fbGqUK+tEYhkNGZqsxGGwg==,type:str]
    password: ENC[AES256_GCM,data:OTLXn2xoWzErBQiVvZeR3YNFjsnCE3UtqPj7O4TrPeOLMSVgnGduAA==,iv:a9QwF3hXY1ZbXy60E4caUvxGiK29vAA5ZeAdbhMYcgY=,tag:HeWoyUcgAXm6Pujm+V5MxA==,type:str]
    postgres-password: ENC[AES256_GCM,data:+hPaotLg+Mr2NkEthtmrbbIFRTAGrJETsOfQSpbOMtcCgccORJQ42A==,iv:UTA3teEij3asDfZaZzrnYYiLiULAYlO04255j8wbEJg=,tag:pErvXFw4B6gPbb9tiE3ImQ==,type:str]
    replication-password: ENC[AES256_GCM,data:3lP+8ZRGwN9WUjU30S4NACowiH4c1z0r1osDkpFBfrdblO1q0fvy+A==,iv:NHgKGDvh1SA9cw4LPFuq68EZnWjoyPoRRMjSqXK3Yj0=,tag:NIvodhcmR7aQ7iLX86573A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lite-llm-api-key
    namespace: openhands
type: Opaque
stringData:
    lite-llm-api-key: ENC[AES256_GCM,data:bgJG5VcA57mF34l+1oLlv7FGv5BQqbFotamX7Qigpv02QmoAYQ1ZE3KcT4CJ0xb8xCLuAn547VjIfLiGE+FKmw==,iv:Tb0BnVBHkjlU8kHE+vbcrXxfOB7Wg2rmm9Y/qAL4Z1s=,tag:IJ8TOAhMvr/3GxPkErNYbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-env-secrets
    namespace: openhands
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:04u7GbCPhBFfE1HWWY5veVXw,iv:kyRZTYwOuNVpL0lSg24Vq01j7+MeYLGj5279I154c7o=,tag:A4FwUzPeTB9uyBqHnW7HKA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:f472YVMD0ecx/b4=,iv:U25c2XY0KE9NPVKIXQpBhyhMgQ2X6YUPIAwuVtrkUxI=,tag:C1qP39RDhrDeprP2jqUnAg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2d3OwehCP+2Vyl2G+NQNXKY8kjLThduqQjOugIrzjWY=,iv:qiTXHmTqmnSUX7aTvXgzIxrooljcW5Bkm7IJ07g7kKs=,tag:HeSvljQbTf54kVXWqx0E2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-password
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:GS1CAzc0+i8XtgVAN1mq5u60lqXeDD5CWJ27jY/0aepn2f49kNKIUGNA9axSbqf7Fhzuddcel6FBpgeoVLDg0w==,iv:i69DZY+O6nEyBPaCZApDiU5uROR5ILYRhrmJGkFFTVc=,tag:55CXMv3fSqkbB/MNOl+z9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: default-api-key
    namespace: openhands
type: Opaque
stringData:
    default-api-key: ENC[AES256_GCM,data:UF7MiuuMF1J6PotgvPg+FaCpH6/o5PvAmx8WHtPhcHtumN9F37wro26NRfIdxHPeNT5v3Pv6cnFlfkSMTBNXMw==,iv:TVineEiwo04LuoYGlNXn1hKODXazkm/8fxs0eVkiY5I=,tag:9PI9E4HHB5bZyLapZtwctQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sandbox-api-key
    namespace: openhands
type: Opaque
stringData:
    sandbox-api-key: ENC[AES256_GCM,data:hTKp4DZoATA/6ljfh6g41bE+ZGWzJ1O6Wtvr1Ykmv1yP+pJsJtCZJcuJL1C6m1G2EjQz7vkZ5Ztcx9ZDcnIzdA==,iv:gW1terkwa8I9ZqI4XZaRNzMknEiQtf9rgeGpw0FE0GE=,tag:11uRsuzJEZF63vnA92tGpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlFaWk03clRRU1E5Yis2
            cnJvUVBEcjB5eDNyVE85K0RMdmdISmRmT1IwCjZ6cFU2ektuMWV3YXdHQjNUOGhR
            K2hZQUJDUHFBUDZOMWlCYTZHZGRmZXcKLS0tIGt1UXhFb0pNQnZzakFGZEZ5L0Zo
            cUc5RG11bjh6YmZtY05HOU5ISm52L1UKMp39poR2VjK287T2fS6a6s6q3gZE7ZKL
            5HjxXR8yqu129GOvMCnjym1rTD7SgPRlw1f6eGWpcKOXfpCQMYs4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:08:55Z"
    mac: ENC[AES256_GCM,data:Reg6+nkgeqELhHWTzwXrWRHx9kXQ8LSdT/GOKQsCgnzy8IfMGN3Unlnwn7tNmF6NZCQUV9Df1EgeQfs19mwxxWMKiVfKu5gI31Uvd3KEcs/4/ETwlkcGLI/aQNhZ64v6n7naG0SjrzNGDWUxqeGJAogsDG2DRmU3LV7auYuAoGQ=,iv:Tg2wTMuohQM8+pfwua5OhZsCziiDgQOk6k3orWmSKoA=,tag:s8CbBkIJGNKz3Z3HvTAUEw==,type:str]
    version: 3.13.0
