apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
    namespace: openhands
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:cJEnYkzvhVZOV73lym4fVMRoYuuTU1UZEE1d5LHBld/PJLvKTY/vq2fouqPqMnpEVmlhMQuxVUH7b4/U1cnX2g==,iv:DSrFOkn+QsSRrnXKPBG3gjR9+4yANPnBrP1aLGUy2TQ=,tag:D0xQ+BZnFc95x9dBDyf6GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-realm
    namespace: openhands
type: Opaque
stringData:
    realm-name: ENC[AES256_GCM,data:bFe5AuKpKJs=,iv:n8a2xMEiBf1b/+FuSLyfPL0x3bdLNUBoEcfJuXwDaIw=,tag:zDhATF+Fh6gXSLNneWBQtg==,type:str]
    server-url: ENC[AES256_GCM,data:AHI03hnSYudgl/zlonSf,iv:DANHyGlwDQ84qSPt1DHVDfGw1HkKkfG15SXpxDy2180=,tag:WwkaTimZF//A4qMZde0puQ==,type:str]
    client-id: ENC[AES256_GCM,data:/wvGSm8IePc=,iv:W2wLbJvg1J+kA3juiQkKwZvYj4kuGxo0+oUVKamT4EE=,tag:YMTK1x2HE9GdFRe/dMk0yA==,type:str]
    client-secret: ENC[AES256_GCM,data:MDT4EY6ZZezLytcr5Fk+B9qTGz5IPkBZXqXFymU3e7Zb/9T5lAENso3xXtwu73JJr3XLPWrBHPOQzJRC8BwoYw==,iv:JoQXZePbfkfrtuIJWGNgl1HDjt+ON/SEqkqhJ9aR4+8=,tag:45Rh50w/TiG1aknHpYGncA==,type:str]
    smtp-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:nozUBhOBMhupiNCDcHyJ6IB82M7fzg0Bu/IXU4tNDsZegAWafp4i1/mMTLKo9eEtmsnjquhaZSeQffenbMJuOw==,iv:PO3uT1kb2AFZ3T8Eb+OwgDZrBK62uW62pFVKJm8P/S4=,tag:RGUCnG6G1BUpbhUdUKRbyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: openhands
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xF9cdnGTVvsW,iv:6X2eY/KkHFoODXVkeEyNNgSzdlhkAzc8EUNgOgdnUgQ=,tag:LEEgfO+iPvQGcxGsp+mUvA==,type:str]
    password: ENC[AES256_GCM,data:CX5MjF74fWge5BbW7d+t4B+fqVLm0Pk1VBXCrQpBx95VTSB8JA1U9Q==,iv:YlaElpVkOHwpcofaMi1hksdGtTJeRskYHXWA8eUgSgc=,tag:SyjnLdEWaAZSvKtd/n0bhw==,type:str]
    postgres-password: ENC[AES256_GCM,data:ge/6QftT0Cbkph0K9QKsaowDFHDACd7rX0B72LIG4GcRHnRGf2aXnA==,iv:w4ZlLiQB+L3fOBvuerPEgIGvt9djrRpazYzr6xRKZ/4=,tag:NKnlPrrWI5hZHuCZnOQpnA==,type:str]
    replication-password: ENC[AES256_GCM,data:MZUorVk5FFHcqQNlkERMK76UvsFNdr/kDYP94TqvRYoT86Pvsy7WHw==,iv:OaHXzbz+BdzTU/KoqVh3k7hLZRKWFRwzFP4rLOAu8zQ=,tag:D0F883uw4oUV8tDeSjcayA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lite-llm-api-key
    namespace: openhands
type: Opaque
stringData:
    lite-llm-api-key: ENC[AES256_GCM,data:vlEoS5iNkZw6giexDVNBRRO1AM/hLdbhqph9fJ6URIavTjG7G/AUkl6o3AUboK50tzvTZa84BNK3a8Q3M9c2Og==,iv:gfRefnY0/d/iXnVT7mno6s0cIII0dLn4DsmwajOn3Zc=,tag:6ZdXiSrKB7Ypw32zCagPrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-env-secrets
    namespace: openhands
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:P5vI0PnX7yQzlbW+OJ2OcRjf,iv:ItV9e1kPMFMfwPj1AcnNJH0iOmWGF/3Vb9QucYLG8jI=,tag:7mxD23BRzciDIzmXPaEWIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-password
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:9QEf9PDqRJX+UAlq5jb+TA3Ycw6K9EOq21CmTIBUV57Skq/Xtjc98oa957v7q8dDP9oPosN/u75dcvnlcBW2LA==,iv:PlZOjFzMXmFq7DfA+meT199lDnYDRPslBTALp3m+G2o=,tag:eP94LzLaTpntNHP8BRWcFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: default-api-key
    namespace: openhands
type: Opaque
stringData:
    default-api-key: ENC[AES256_GCM,data:3sqexOF9ofBr9LBp7zXcSIwrDghcmKafYUC3onaGsCYFTSPucbwRaIpXDpKUmXtkRsgtQAkmvMqkBJIdrCtqWQ==,iv:JxuC/mmkY1NoToAr5hU2hoE1O+0DAA6AngXVK7rSiyM=,tag:5GNWm3eM70x+CvxBdjunLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sandbox-api-key
    namespace: openhands
type: Opaque
stringData:
    sandbox-api-key: ENC[AES256_GCM,data:0oR795aR+sYGjfI06XRvy3Ds2WFRBc6w1HQMBEZE1BEGLZVsVL3epHleaG19BcWBn+CAhjq9XblogiXRkgzT0Q==,iv:YN4ONC2wxRPOQUqtrTrg4TBdsGxeW1TRoRj9QdchoA4=,tag:A4MUxOemMIcQ+e+e1d4JNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3lPRkM1bkd4ZUs3VGFD
            YSsxc1V0NTZvL05tWlUya2gzRWpUaWNUdUU4CmxKV1c0Z3JZcTFwK2NQdHJYMmZp
            OFdMV1R2RDBVemN6TjlrQ1BMNGNSMGcKLS0tIHRZU29BNllneGRibjZ1NmV5alQ3
            ZnQyYXcrcVVkYUMvY0RiYW5odFZna2sKts2T+u3vvmLs4KSvlPcayprhhQKDzBwV
            k3L/0XQWSj/XiJgf4nyZjmC6XLsNY7K2hUUq5KdEB6Nodmu/793CJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:44:31Z"
    mac: ENC[AES256_GCM,data:T58xOO9pi55W1q+zMcKoTloRs5jXrIAs/5ku424lGQYRaDmg0FRGdapot3AW7YvLgEcswTypAZg79U7jUz6Dcv5HgyXjxQXwIXOEZ5nyZOrm16rj98DhelIvdC7nhiAbYm9Ov3xl7DMvT84q4X+ROoxNY/Ndunjn8pZ8GUttGm8=,iv:K0xVuIS+Y+/E+yFkYyz/wcPREGV2Z5cVfl3dGD7cUzw=,tag:1g92fWWF3bRfsROUmrNh/w==,type:str]
    version: 3.13.0
