apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
    namespace: openhands
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:gK6/lKu4BLVJbA9Dw3ozZrIw5GKQWbUieA2/CiEgbffgmgnG8DEyAo7ZSB1MA6eK6tUOUtfOB0+W+ax/GpuRSA==,iv:8TMcHHYRguG+uXru3gQJ56NwKmPuJoCZd0FMI6cgsyE=,tag:MPXYe7xbuxHhvsThJ6Cqpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-realm
    namespace: openhands
type: Opaque
stringData:
    realm-name: ENC[AES256_GCM,data:h5BI7h6u3ho=,iv:roPSIZpjYyn/RpWv+x0ijPi5s4pSP6EgaTdSlVLQFpE=,tag:5ahKnntbzjTiN6mXVWiajg==,type:str]
    server-url: ENC[AES256_GCM,data:KL2IfcWDklxUIsikUV+L,iv:+yBDzEQ82ZaWSEYV53n7H02KuB6rYa9Xknc1dI5hrns=,tag:qS65sXUvJ1+2Ph1Ho5yg3w==,type:str]
    client-id: ENC[AES256_GCM,data:o31sESzePwA=,iv:mKWoC0OoTfrcSbGRcoD1wig/X5hcIPzzyjTiTVtqrp8=,tag:MWWqu+kkeXHI9DiE4jtQPw==,type:str]
    client-secret: ENC[AES256_GCM,data:FwV3by6CMTjhMFGbNaP94DKfngMKdy0S/ySGx4uGREH6nZlI7IgBFymsP6U5DNo5rdKRnL/yvWczJ5ViCr/yNw==,iv:BpzLfubTXPYNc2jI0WJucSEaAASHQQTFPltin+Oc5Qc=,tag:PSNNt8EnZE80PhCD5ThsuQ==,type:str]
    smtp-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:66JQ4wGS1SDmmQk6s3b60rkaCIr6Wx4/CfOJak5pv4ys6HyxlXyQFFIAtKJvD84p5WjzYFblrL0cce6Iz+O82Q==,iv:6ArgTBQXQmQilUodkZHOVCajwkDfbEUgcj39r19j31k=,tag:jWVkzsjTNy+/orj8s9QtnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: openhands
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qRAvYnaRrE56,iv:mN9H2Z7rRYyaTwenYIwFGhez9n9KPecTusa85RwIOmA=,tag:k52XkgrSsec9O2FYnMGpZA==,type:str]
    password: ENC[AES256_GCM,data:Af3oTAsSmMWXfNLyp2IFB4Lz/h9lrASdKA9vbSTzm+Z6eJAfg2IW2A==,iv:evsQKr4nLqseQprRq3N+E//ynbnhMzwkJU59qpI6Gu4=,tag:Lx+X9Um7j5jBVz448SJkng==,type:str]
    postgres-password: ENC[AES256_GCM,data:vQ3BltjPJjWlsUhK8jK/+NJZrWtQGwXK2BCmaQDh+55xEuxBVzmFQw==,iv:m2rrj8OCAo5Sb80f761gulwASv1L62OOfwIqintzl6M=,tag:vueWV4CwiPL+0y9OSS7whQ==,type:str]
    replication-password: ENC[AES256_GCM,data:bqjBzhnCFyrhW9scu1x9s/+HblRIOcLsTynapqMBK8A39GDEVW++qw==,iv:WhpkkrkkvTOrHG0FR/bBEV7uHKhUQUXEF4EDVUegY3I=,tag:YyEA5f5Zwy+LUDh5n4TLkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: openhands
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:/w7lTlFEVfgy1jTP5a4HwGh3ssN/CC59cVOp8boo3VZDLQ+RhWSkZKSU922PNm3w7Wppno09DI+oTwi1/2SqtQ==,iv:pFLxBCsaATu/mAfN7phmdx1QTxOEDXFk1ciXQCH8qaE=,tag:LDvySlR98zTuxZYsgv3Rfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lite-llm-api-key
    namespace: openhands
type: Opaque
stringData:
    lite-llm-api-key: ENC[AES256_GCM,data:w1tyRpgL24mg5/CNI5GxmaToRY748dSXTW1BY2ojREQ/SuvtYLwHlVUNzEEhKf1Oq/FgsSClWTB8O7QZFIum2Q==,iv:rFVi+8fRYXQNG0SD0+THesoA86bWSMkFfcv7ATkh8FA=,tag:Y2Zs95S3rvi4CFXjKgaPEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-env-secrets
    namespace: openhands
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:KZnLlLzuLZqIKUBsq48o1d2g,iv:e7siuNLCXu1ComJawvqeRp0Pa1v0g2S102UWAgtpfsg=,tag:kkLPoC0sApNf1Y5XZU8kNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-password
    namespace: openhands
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:ZnimlW+HBe5tTIzesfVkXWmpb6EMRFOFd18ZWllnIP8WSWn2v99TSIRP4V9Vsvo420Vxzpko2jSMb7f4va6HwQ==,iv:EFX9uwg+8kh+zh42k7ZHkaDn3FMIQ7QCKwodvsKachQ=,tag:JCd7dPylOX7nQgb7t2Aupg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: default-api-key
    namespace: openhands
type: Opaque
stringData:
    default-api-key: ENC[AES256_GCM,data:RRX45AEmhcnZeD4MUrhROBGjrfEAOtJD8x+3nD/Ca03TaQ8lmSdpzAnIVJKTOcHCv1A82ymYY1vCyV60S0HrrQ==,iv:QuijNHPjIDCWLS8QwITT58fmdMl4O1+V+xeCY8e3qDk=,tag:4OKvjTngt+TD8TGeTFMAfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sandbox-api-key
    namespace: openhands
type: Opaque
stringData:
    sandbox-api-key: ENC[AES256_GCM,data:XR7aXUpkkgJwdWADUyw4hjbMN1JjcN2iN7BFMa/9qc1uvfoZyslcX8MUqg6f1arSJuFKoVSBe3RR1stwXZCi6A==,iv:vLorYdXPqO19aU3Zwv68q9UO6m9DJI5phSkMTEez0vo=,tag:d3x+vz0+0rX3jBPIuOYnkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzNrWHYxY215VE5Oa00x
            QVduZktUYzFRM2pXVnZHYVQ5WjQ2blF1d1ZRClVoMTBlRjdUTWxVVzRENDRyT2Y2
            MDkrRXZ1Rm5CaTRtRThKS0RVRllUb0EKLS0tIHgzNkNmVUNjc2FjWDVmcW1KSmlE
            azRMbkcwSXlmNVhsc1V3RmRSYUtrSkUK71CwjxoMCZVvf6GiGfT/v+XuGMD1xFVp
            3rBIXNH2Y0LUg/9JJWEx9+ygoq6w2lyp3bGXXdeYMpMOwrqCaKplOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T20:55:34Z"
    mac: ENC[AES256_GCM,data:aASfS/vUnL9TkafXMapqB3b++cDO4zUybdwRTQDj51c0M4wBiVZAfC2QQh3+2VZW09qkB7KbkG5E5RJqMBcfb8oxfB7HK68+PNDDlYGxt3iibpFeW+c6VzmO2/isxIvkfa05WZUMcW348IsRIzEopFkOv6D3EVK7z9l80YfIPpU=,iv:BtzCjLZ+6/j8523TQ2xyztR+ev7qZWrcp0nADycm3Y0=,tag:B2d0bI+Dl5oBl7ZrlE/3Dg==,type:str]
    version: 3.13.0
