apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secrets
    namespace: ghostfolio
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Y0m4QkxykGnyZn3/vDLUnAbCNbmi0mHW,iv:osJhNOSmq15hP2FLJgl+/n4SU5CZyw7FiISeyu4M5iw=,tag:5IJDJmo7piMfndfQT2t6Uw==,type:str]
    redis-password: ENC[AES256_GCM,data:yllntdRwwzYG+eDeYkNRBT+VIlGbqWoC,iv:cuTlDGSgT5Gg8tCKRTlPLV7zPB/ngHHeMBTAQA5v3e0=,tag:HXKd8Iec4H1V7zT/1LCWpw==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:hV0PhFHZnDcDyJfI3BqEH2zbWjDA013llE/n8I5jaLs=,iv:9Nxc5NWNp9REFEfGzZYdaFdpV4aGdjXFAzpEEIuyA/I=,tag:pBdZXaV1voZFGmqG/tgjNw==,type:str]
    access-token-salt: ENC[AES256_GCM,data:YiG+yExHuag3WpMOXahGPYRR2jYD3eJch8boaimtXT8=,iv:DG2LF8QzOlICWjJ38LKSkWogeYt2o7zr8TGHe1XsXkk=,tag:uOr9APZ7SOY2QwQEvLv21w==,type:str]
sops:
    age:
        - recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOVpyZ0Z5QlFVaXBpOTFa
            cWZmeHA5MXRlaVZBQTZyMVpzdjY3UHZiY2dNCktxM0xwNnlnQ2NIcXVLZFhxaUNk
            OW5lbE1ZR1FuVnY2Y1haQVU3ckdrdmMKLS0tIDRCcnRjdXhVeDVTYkhOVEdVUnhx
            VnBmOWVVUE5Fdm1LcUl6ZlFOZlloYWcKJVohntcNliJwB0p67RfjR+YpdYoOBKIw
            +QI9vmRggvcfSQIJFd2nnPk5yoSQYTopdSVa7SHU49bGeyCJNvRnjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T04:15:03Z"
    mac: ENC[AES256_GCM,data:W/lHUvx1rp8w+nsmNJHgabwpw5bdvX1U9dNxFCgW8kuA4OOYYNInwuh3F1Zty5NFJGmghuOba2XD0pmGNXHRjAVsBLoMvxiSp8FCiRfjvwY3xIWIkuoSwha1pO3+u2PoI4JZatT+duaFWGYykuuVrvjAvku9eNlHP546+TKEF3w=,iv:SMw4csWg7aa8HA3CrsiKY4iFgMZYyHXnrbmmHIbjx5A=,tag:Cb6ItZFfhQxnBEl+8Rx91g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
