apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: minio
type: Opaque
stringData:
    root-user: ENC[AES256_GCM,data:Jwch7OEgMTDKsco=,iv:0mzk3BZAVHFUkCIRNoadLY5f7Vz3GMb6qDmDc14O+Qg=,tag:jU1Qed7Sg3wgIUOdOXxsNA==,type:str]
    root-password: ENC[AES256_GCM,data:un5CQlKp8VnXKAgYq1hiNWZJ7JJGL7Qpw1CyLDbIWbk=,iv:d5PFqN0j442ejFat1huF8U0WOYlCtTYh1PVCoCHllFc=,tag:HONzF9Q+3gqzysuOGJlVOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUW9TNmdrQWN5R25IMnhE
            TlNEdHE3N1MwYVM4U05sdjJCeXVvQlZNbDJ3CkNMVTdjaXpsd0dRT1VmTUEwZk9Q
            WEVuM0hlODFBVWJsMGcwbEQ2c2VUYXMKLS0tIFREU1hpd1dnaXRnL08rdEZSNDNU
            M2dCR0ZGVDRsZnhZdlhGVDVqR1NBaVUKwWA4iaErVcTETMLNTEYsZC8Lf0aU+nzo
            lvgaFGnteh89X/VwNGG3Lc8Emdovm48G31tCJa6NojmDdWSo5zokdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T21:37:22Z"
    mac: ENC[AES256_GCM,data:vsxuFvpn+DHMHHt7AECmxowSsmYJUkGbmi5Pu3R8q0YhJ/28WmhtGBqx5idpz8UUZZ+UsZDEtwgKcezIFqowY3N1ANjEnKekyaUOVMmExvtcxxgH9rxelRd4Hjs77giWuApPI6Lf+5SMUbfRWPP+Q8Bx6jxkB5EjaoEj5w9HUVQ=,iv:6HHPwPjFhTAngyRbTyqRu+UMd0G7yJPb680TB1AcFmI=,tag:HJlX4t9W0AOzPDpGdeWz2Q==,type:str]
    version: 3.13.0
