apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:wwE7BmDyMRENT9+44NOEoS2KHq09Vc1oXLeADJI0ZxO4lNtHJFKF/Qxd+Yaz8oGGFPVu/amET75dKH/bY2+A08hkXU35H91z+hehWtYsGlHPR+m31+PRLceblfBcuwmcjtWP9G2GJCl93d7EK/wC759s/as8beMYjTPeONJa/FuF358GTKJy1GiTfZTDkKCrrReUwrt7ocoGA+AXCLTH6pZjUZJDQ2SdyCj/Z5M5zNmbyhkRXGqqRw==,iv:1pJp/8zPZ4pn7DdezhCzYGGAL9on57uIcoCsC160/9k=,tag:MQr+sQZCNlpOh8PyJb1OmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTk9MV01LL0t6a3JQYUVz
            dkdGbTQ5emhGSlJtU2hnZ1Z1bWVPME1sUEJFCjNTMS93Um4xVGlxbGxXakJIcHlS
            V1NzMndrUlRvMXBZVGZrM3A0eHB4VkEKLS0tIE84RWI2a0kyV05vZEtTbU9HR2po
            dnVRa0NKSlQzYVg5UkxGUVlhSmcyZ0UKUQe2LywM12q0ZzvU7ulowyoKRryeVapR
            wXZm2+rSFoLVIRl+j0jTVAQPe7EfdRuTKEnEaudH+jhNx6vOnbUxmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T02:22:38Z"
    mac: ENC[AES256_GCM,data:Gyfb1WQfcxvAMV0dJoCdzfxK8qlIcHMrPClP/5MWZHRtyco3EohKya/YH8/2Hj4LlDw+CFn4Z4RvS84gQNp1FepMBqn42J9PFj/oZujspbz7caIBj8xdPec8Tj1J4NX1sfxtgn6QmB41XfEJj6t2aYv0QsHP4hQ4A1U+3uW0wvQ=,iv:rQqS94qh6XAxcOYnaGm0oaGdBUHoA5AtCDQgf5qZ+xo=,tag:m27fn59OFaViWLV2/mVt1A==,type:str]
    version: 3.13.0
