apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:lRvpIdeeCNhjWPIKI5hYS2uMLqHAgqV64C2WHpoT+neWenRhfdj8NgHa96afqeQi+i9WKXocWvi9vRU3xlUwizZucHFSce/Z5KkmxuzR8bcwTaviCnh0+u/1VjdRBoLArMD9g2C49XCu0kyNJ59B2emn7I4NAmAJXAEUNzb0lF+UYniGBQLoXq3IgcCj4u2MYMG0Js+z7TsICaYn+vO1bNwxs2Vr84yaveZyWL/jz3FFOWoOx7ySwdke75gHNLWHIZWTzJoIBdp6LHtMKA2IicmOfxOohPBVsJp3H+1IchdblApjRzHxuzJySz80EAfAkEdnF4C7eUs=,iv:9DaBI0ttlQU5UagmSBO/bEQKC11adoPSMBdfVkB8jDo=,tag:dNNtAcQwjXSPS40XCSDRIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTk9MV01LL0t6a3JQYUVz
            dkdGbTQ5emhGSlJtU2hnZ1Z1bWVPME1sUEJFCjNTMS93Um4xVGlxbGxXakJIcHlS
            V1NzMndrUlRvMXBZVGZrM3A0eHB4VkEKLS0tIE84RWI2a0kyV05vZEtTbU9HR2po
            dnVRa0NKSlQzYVg5UkxGUVlhSmcyZ0UKUQe2LywM12q0ZzvU7ulowyoKRryeVapR
            wXZm2+rSFoLVIRl+j0jTVAQPe7EfdRuTKEnEaudH+jhNx6vOnbUxmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-13T20:32:16Z"
    mac: ENC[AES256_GCM,data:g/wVoEPsYqGXkYbveN+ClEc2MFpVXtTYIEeZS2E8Bj3ku2clJmjlEGCbc6KfGvkt/v2XAIOCuo3MNQ0kgcrm5z0MMkCkzmQ0EpoWFs2l5qT/DGXssLZKQH25R4EI5BhKdSd7yllI7JRvjCSOopSMNF2bxvp4okSmKBlHesz2AQo=,iv:nG8/QlY9wrBqhRgEAYtf2NcWottdDMU+yCpXZeQwHJc=,tag:0NYiWC4EOm9NqgukidsVFw==,type:str]
    version: 3.13.0
