apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: maas-dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mcAcBEGTJIZS2qXMXFe4JAAFqI/GHELX1FVhx9b5+TKYJazI6+KtgX6vgqBWsW5PVKQuGzDFkluVqE8RHFkkOYwlGXnyHKZFv9rDhqvh95veAPcMa1pEhMxsFIdayVzABhQ3QwUDwrMgkSwhB356BdVEzZf8vMDhh2aFBE7Es2z1SeEC+VOdNyyWTDdy,iv:pUtH3yD2Maf2mg0S/pqvYmklK+tlKQns3OAd5CQz/Hc=,tag:Dwxo0TbFP1gbxGRvXOhAAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZkMwaG1yT1JoMWRRWk5n
            QnZ1bnN6ZEg5YVFhRURWM3I4VjU4eG8yWGlvClQ2SzBDRzRkcVAwWFROYjNDaXZS
            dm55TmFZNUphN2Z6TGNTa1J3M2prSzQKLS0tIDMxSGI1Z3NKYVB1UzJnMXIrTTRq
            a0gvWjV4VEdEZkhzbWxBK3A4d1cvME0KvX2FI4DWLol+Hi0+YMhkinQBTqKVp7qh
            q9MOttJpFZl934VFyJDuBLuvewAeDmDfepDiGlzfMEaDK7kVroX76A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T20:33:16Z"
    mac: ENC[AES256_GCM,data:sUzgGjjEDy59VDzxnw4CmRt+rN+8cIPgY14OpgnY8kc5UIkKF8FsACM1+onhduhDaeOCNcuOJi1d/KlVXicOb4WeuO0W898mwrZ9Nr0dgwQH4d+hgwL5aDT5EsSuDXql/DTplmZnaa6bN42CA4U+q5DvKjNlrJuiFcKOg10H+eM=,iv:jMg4K2S1c/7B4x3ObZJXrmAuSJIvQlBctEGWw+KdxK8=,tag:bgIdz4kFut131ZPbk0MqlA==,type:str]
    version: 3.13.0
