apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - git-storage-pvc.yaml
  - zoekt.yaml
  - runkod.yaml
  - runko-watchdog.yaml
  - runko-mailer.yaml
  - web.yaml
  - web-dev.yaml
  - webadmin.yaml
  - runko-deployer-secret.yaml
  - runko-deployer.yaml
  - ingress.yaml

generators:
  - ghcr-pull-secret-generator.yaml
