apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - git-storage-pvc.yaml
  - zoekt.yaml
  - runkod.yaml
  - runko-watchdog.yaml
  - runko-mailer.yaml
  - web.yaml
  - web-dev.yaml
  - webadmin.yaml
  - runko-deployer-secret.yaml
  - runko-deployer.yaml
  - ingress.yaml
generators:
  - ghcr-pull-secret-generator.yaml
images:
  - name: ghcr.io/saxocellphone/runko/runkod
    digest: sha256:02b5536fd71b5184ac6da5f94baa290e9324364d4d8e98552ebd366d870c2278
  - name: ghcr.io/saxocellphone/runko/web
    digest: sha256:ec776326a1037c8e81861c61bf85d3887660a189d1a7ff15c54a2f7b59bcc6de
