# runkod deploy token (REST bearer auth + pre-receive shared secret).
# Read it back with: SOPS_AGE_KEY_FILE=./key.txt sops -d apps/monorepo-platform/runkod-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: runkod-env
    namespace: maas-dev
    labels:
        app.kubernetes.io/part-of: monorepo-platform
type: Opaque
stringData:
    RUNKO_TOKEN: ENC[AES256_GCM,data:dPAYfLyNCakYoMsJ9uEmt+2X5Boof8BvTbzPdO1R4tqgrHBHZ9y+YPNBfXYxLCElPLVRirCDZjFdyVHYMMTKsw==,iv:iAhstOEHHT5eSQWbFxP/fdjqytOGZWRjjWwWVPW/pDo=,tag:jsKw4o2lT4Xu0N/6qW9JUQ==,type:str]
    RUNKO_WEBHOOK_SECRET: ENC[AES256_GCM,data:YHhiqSDzyCLySRLcqmGX6l8OYUF5dZrgMWs5aue2lhEVuC3E00qEzdvUDjFkZIlY0aDooJKfAC0DsWaZA5HWGQ==,iv:7urmdkB2AChNmbTKoUls229OxjqTRQZ65ASO3U51Ldc=,tag:/AZr/nEMLczNd5tFFNflxw==,type:str]
    RUNKO_ORG_MIRRORS: ENC[AES256_GCM,data:8dvZAOkW/zJ2TxLl9TzUZgDuKi0Fbtb4JXFeZsfWuQHloi9Pe6Lwm7tskKj4CzaKCu4YofNGszi8c1j6ZY0sa842sqJKMeWf5aO/P8IkEZ9BC5E6ZcvXUAlUhq9jryRvwVP6vCTwB5SQeHQnd5iZnjSGMki+iRWRwLjeU20UBaMgZF08ScpL1QmaQTrWoIa8Seiv3lHQG+LvbaTEFg60giQJZTJVBUWHwzZw0dCyq7I6uyIOUa5u,iv:+J71tb+1RVL2GgfZYWWWXOtd2AzQtWyOIaK4qY58kq4=,tag:6pJYk2Qs0gtXzttj9uWjVw==,type:str]
    RUNKO_PRINCIPALS: ENC[AES256_GCM,data:xollAJ4jm7K0eDSY79UN94yfBv6UA45OCWifTujXmeCqJatA/J3dOlMovOXY00TBn0SuGr63DAaBrTVmUk0xKGAU4siUjJmZG+ep3YBFv5ZANiF5uxpnd4JhH9nwGNsiY0pcaJc85xXGVgXbLkZrsVG2Z3I6xWpzU767OFGvYxA8Pmwe1+Oi0KPbjQAcBodxljp28AbkdvmzXv6NUBwzx2UGV/t1YgS2+K+IlY+RgWI=,iv:SXKEOr5z3XF2A/3hKefSq1j6xcihqEl/ObDZ1X+1AGM=,tag:2r3lpVZ8Dac3D8AzFyiYig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZGxmRnRzSjQ5OTdaRG5L
            NHhzQ1B1ZFJzTmkyZFZGaU4yVmN3UHhnSkZjCjhLaStHUXVZNzJ4b0oyeEpWK2lw
            UUNSVFo0aWFjRVYwLzA0cUI3eTJsM0EKLS0tIFl1VU9mSitiTzJuZWtyL0VxVnJp
            VWlqZ240VWw1a24zUVB5c2QxVEtibzQK89O4DwmB2jyXjSkcWP0/wZ5FFKU0qi+r
            re9q+RvBaGGf7W95bf0EtM2u2i9U5MHSTFdqQa/sYYWXTXQfsjfUaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T17:32:45Z"
    mac: ENC[AES256_GCM,data:xHGgAk5HFUyBg60Yp0EMNi8jkWbg0LPCgxPiyWHsvDzaDJgnPoscQClNs/9oCx4zo0dsdJqlUCuLYdqo354+mly0NiSU7nDO5NIETRSqGAHVeLaJ2puET/W9EOis+y+IPIgJGJQU4zNbLUj8jyZAnSAPcbXfpq0RQLF+ybfB6sU=,iv:1JGtTcXKAnmZd8ivXrZPZ0GJI8mzYkORiLz0Kob5Rt0=,tag:G4vpgf4qDrSQO2qSYPRjfA==,type:str]
    version: 3.13.2
