# runkod deploy token (REST bearer auth + pre-receive shared secret).
# Read it back with: SOPS_AGE_KEY_FILE=./key.txt sops -d apps/monorepo-platform/runkod-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: runkod-env
    namespace: maas-dev
    labels:
        app.kubernetes.io/part-of: monorepo-platform
type: Opaque
stringData:
    RUNKO_TOKEN: ENC[AES256_GCM,data:dPAYfLyNCakYoMsJ9uEmt+2X5Boof8BvTbzPdO1R4tqgrHBHZ9y+YPNBfXYxLCElPLVRirCDZjFdyVHYMMTKsw==,iv:iAhstOEHHT5eSQWbFxP/fdjqytOGZWRjjWwWVPW/pDo=,tag:jsKw4o2lT4Xu0N/6qW9JUQ==,type:str]
    RUNKO_WEBHOOK_SECRET: ENC[AES256_GCM,data:YHhiqSDzyCLySRLcqmGX6l8OYUF5dZrgMWs5aue2lhEVuC3E00qEzdvUDjFkZIlY0aDooJKfAC0DsWaZA5HWGQ==,iv:7urmdkB2AChNmbTKoUls229OxjqTRQZ65ASO3U51Ldc=,tag:/AZr/nEMLczNd5tFFNflxw==,type:str]
    RUNKO_ORG_MIRRORS: ENC[AES256_GCM,data:50OiDSKxC0SQOiiwzREgRVvROZJsbuF3ALvp4/FqL/nZkTpKgwU59NlITj18dwt+LvOWLLw6cET8Wgs=,iv:gIUKyUrpjh+Br+KQfbeAajGOBRdHA/axUKGehZB9TKs=,tag:bf/KVRTGHNhnjf1YWxXohQ==,type:str]
    RUNKO_PRINCIPALS: ENC[AES256_GCM,data:xollAJ4jm7K0eDSY79UN94yfBv6UA45OCWifTujXmeCqJatA/J3dOlMovOXY00TBn0SuGr63DAaBrTVmUk0xKGAU4siUjJmZG+ep3YBFv5ZANiF5uxpnd4JhH9nwGNsiY0pcaJc85xXGVgXbLkZrsVG2Z3I6xWpzU767OFGvYxA8Pmwe1+Oi0KPbjQAcBodxljp28AbkdvmzXv6NUBwzx2UGV/t1YgS2+K+IlY+RgWI=,iv:SXKEOr5z3XF2A/3hKefSq1j6xcihqEl/ObDZ1X+1AGM=,tag:2r3lpVZ8Dac3D8AzFyiYig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZGxmRnRzSjQ5OTdaRG5L
            NHhzQ1B1ZFJzTmkyZFZGaU4yVmN3UHhnSkZjCjhLaStHUXVZNzJ4b0oyeEpWK2lw
            UUNSVFo0aWFjRVYwLzA0cUI3eTJsM0EKLS0tIFl1VU9mSitiTzJuZWtyL0VxVnJp
            VWlqZ240VWw1a24zUVB5c2QxVEtibzQK89O4DwmB2jyXjSkcWP0/wZ5FFKU0qi+r
            re9q+RvBaGGf7W95bf0EtM2u2i9U5MHSTFdqQa/sYYWXTXQfsjfUaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wxcpw5ppd6zc5dmqn69dxczla0vwa3es086u654l8y2mrj455nqzfapl2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T17:58:47Z"
    mac: ENC[AES256_GCM,data:pbGuS6iZW5w//RCKU/vlZ6CjY+RPLhEYAEEsS53pdfkHk+TSWJe7Vg5ywgLh82jGxCNHVF+XBDKyhqCUCy1Vg9pCvDKHVdjlw6akIySCyFcy7HmTrzpGXnDdgbN3DrCSlGYg+p2coW2tWgKGJzZ7tLGXMSipsAEnD9yiF8+4aNM=,iv:nD+tBh59SIm+fIhtzURKVGn01+eQWm2uoatKMsca71U=,tag:xDr3u1YsE63BKQZ0An3BqA==,type:str]
    version: 3.13.2
