apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolf-state
  namespace: gaming
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolf-docker
  namespace: gaming
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 80Gi
